### PR TITLE
adding metadata to fix localization automation

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **Line 81**: **[Error]** W:\cajc-s\.optemp\packages\opbuild.scripts.1.61.1\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_prebuild in the docset PowerShell_PowerShell-docs_reference
 - **Line 80**: **[Warning]** Failed to run script W:\cajc-s\_dependentPackages\CommonPlugins\tools\PowerShellReference.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808070230301669-2787%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PNPEMrHK%2BmANFI5q956M9QVaPJJSwO0yPqcVjVkSkz0%3D&st=2018-08-07T02%3A42%3A19Z&se=2018-09-07T02%3A47%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by qinezh** [comment]
Reopened the PR to trigger a new build.

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **Line 81**: **[Error]** W:\xhxh-s\.optemp\packages\opbuild.scripts.1.61.1\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_prebuild in the docset PowerShell_PowerShell-docs_reference
 - **Line 80**: **[Warning]** Failed to run script W:\xhxh-s\_dependentPackages\CommonPlugins\tools\PowerShellReference.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808070324336184-2787%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Ai%2BcxAU1YUvbbvmIl4tgPmBve6qpy065O9HXj0URDWQ%3D&st=2018-08-07T03%3A34%3A29Z&se=2018-09-07T03%3A39%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateModulePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step UpdateReferencePage failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **[Error]** The step GenerateReferenceToc failed, Could not load type &#39;System.ValueTuple`2&#39; from assembly &#39;System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51&#39;.
 - **Line 81**: **[Error]** W:\u1ke-s\.optemp\packages\opbuild.scripts.1.61.1\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_prebuild in the docset PowerShell_PowerShell-docs_reference
 - **Line 80**: **[Warning]** Failed to run script W:\u1ke-s\_dependentPackages\CommonPlugins\tools\PowerShellReference.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808070449340806-2787%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fBF%2Fheun5OMRG9Qk4Mqa10PKCaZhWgT%2FpPHp4FZazho%3D&st=2018-08-07T04%3A59%3A50Z&se=2018-09-07T05%3A04%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/PowerShell-Core-Support.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/PowerShell-Core-Support.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/powershell-core-support?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/powershell-core-support?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/powershell-core-support?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/powershell-core-support?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/powershell-core-support?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/core-powershell/WSMan-Remoting-in-PowerShell-Core.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/core-powershell/WSMan-Remoting-in-PowerShell-Core.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/wsman-remoting-in-powershell-core?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/wsman-remoting-in-powershell-core?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/wsman-remoting-in-powershell-core?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/wsman-remoting-in-powershell-core?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/wsman-remoting-in-powershell-core?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/core-powershell/vscode/using-vscode.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/core-powershell/vscode/using-vscode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/vscode/using-vscode?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/vscode/using-vscode?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/vscode/using-vscode?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/vscode/using-vscode?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/core-powershell/vscode/using-vscode?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-linux?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-linux?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-linux?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-linux?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-linux?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Windows.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Windows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-windows?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-windows?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-windows?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-windows?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-macos?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-macos?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-macos?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-macos?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/installing-powershell-core-on-macos?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/setup/PowerShell-Core-on-ARM.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/setup/PowerShell-Core-on-ARM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/powershell-core-on-arm?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/powershell-core-on-arm?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/powershell-core-on-arm?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/powershell-core-on-arm?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/setup/powershell-core-on-arm?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |
[reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-locmeta/reference/docs-conceptual/whats-new/What-s-New-in-PowerShell-Core-60.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-3.0&branch=pr-en-us-2787) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-4.0&branch=pr-en-us-2787) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-5.0&branch=pr-en-us-2787) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-5.1&branch=pr-en-us-2787) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6&branch=pr-en-us-2787) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808070603562858-2787%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eP8UeXWilKt1tRYpy9TTd%2F7t9pz12I%2Bh%2FK2lZa4fgpw%3D&st=2018-08-07T06%3A13%3A29Z&se=2018-09-07T06%3A18%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
