### PR TITLE
Repaired bad link

### PR DESCRIPTION
**Pull request by skycommand**
Replaced a bad link with a correct link

Version(s) of document impacted
------------------------------
- [X] Impacts 6.1 document
- [X] Impacts 6.0 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [X] This issue only shows up in version 5.0, 5.1 and 6.0 of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider/Get-ChildItem-for-FileSystem.md](https://github.com/skycommand/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider/Get-ChildItem-for-FileSystem.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/providers/filesystem-provider/get-childitem-for-filesystem?view=powershell-5.1&branch=pr-en-us-2672) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FProviders%2FFileSystem-Provider%2FGet-ChildItem-for-FileSystem.md)

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FProviders%2FFileSystem-Provider%2FGet-ChildItem-for-FileSystem.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider/Get-ChildItem-for-FileSystem.md](https://github.com/skycommand/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/Providers/FileSystem-Provider/Get-ChildItem-for-FileSystem.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807080726322415-2672%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OGokOz7iJvdZg4fLKQnBn%2Bzk%2B%2BtwP6zyR%2Fzdc6InCOA%3D&st=2018-07-08T07%3A31%3A49Z&se=2018-08-08T07%3A36%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by skycommand** [comment]
I am not sure I understand your comment. I didn't change the `locale` metadata.

**Comment by sdwheeler** [comment]
Thanks for the contribution. 

This content is broken in a lot of ways. It is not published to the web right now. We are in the process of folding this information into the cmdlet reference for each cmdlet. Closing this as `won't fix` since we have other plans.

**Comment by skycommand** [comment]
No problem. My first `won't fix` here. ;) And looking at the state of all Microsoft repos, there are several signals telling me that something big is being planned. I just can't say if it is related to Microsoft Docs or the GitHub acquisition. I'm getting somewhat curious. Do you guys have a GitHub blog or something?

**Pull request closed without merging**
