### PR TITLE
Update install-configure.md (removed Win2k8r2 x86)

### PR DESCRIPTION
**Pull request by Ndragonawa**
Windows Server 2008 R2 is 64-bit only; it does not have an x86 version.  https://en.wikipedia.org/wiki/Windows_Server_2008_R2

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C27%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701271405047642-991%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C30%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701302131491807-991%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
Thanks @Ndragonawa. To solve the merge conflict with you origin PR, I ended up creating #995.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C30%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701302150453899-991%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
