### PR TITLE
Update winrm security to cover 2nd-hop scenarios

### PR DESCRIPTION
**Pull request by eslesar**

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[scripting/TOC.md](https://github.com/PowerShell/PowerShell-Docs/blob/update-winrm-security/scripting/TOC.md) | :warning:Warning | | [Details](#user-content-scripting/TOC.md)

<a name="scripting/TOC.md"></a>
### [scripting/TOC.md](https://github.com/PowerShell/PowerShell-Docs/blob/update-winrm-security/scripting/TOC.md)
 - **Line unspecified**: **[Warning]** Invalid file link:(~/PS-remoting-second-hop.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612130054083757-900%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@eslesar, could you please fix the broken link in the TOC.md file?

**Comment by eslesar** [comment]
@juanpablojofre Fixed.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612131825489772-900%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
