### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by alastairpat**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612061030498139-881%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612061929350657-881%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@alastairpat  Thank you for your contribution to make PowerShell documentation better. In future, please make the fixes in all the version of cmdlet help, where applicable (in this case reference\4.0 and reference 5.0 as well).

We have taken care of those this time :)

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612061934437372-881%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612061935370352-881%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md](https://github.com/alastairpat/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-FileHash.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612061943375624-881%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
