### PR TITLE
merging recent changes into live

### PR DESCRIPTION
**Pull request by eslesar**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/dsc_roadmap.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dsc_roadmap.md) | :warning:Warning | | [Details](#user-content-dsc%2Fdsc_roadmap.md)
[reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md)
[reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md)
[reference/3.0/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_WorkflowCommonParameters.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md)
[reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md)
[reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md)
[reference/4.0/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/PSWorkflow/About/about_WorkflowCommonParameters.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md)
[reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md)
[reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md)
[reference/5.0/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSWorkflow/About/about_WorkflowCommonParameters.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md)
[reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md)
[reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md)
[reference/5.1/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSWorkflow/About/about_WorkflowCommonParameters.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md)
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/Invoke-Command.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/New-PSSession.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Management/Restart-Computer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Restart-Computer.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Utility/Register-EngineEvent.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Register-EngineEvent.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/Invoke-Command.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/New-PSSession.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Management/Restart-Computer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Management/Restart-Computer.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Utility/Register-EngineEvent.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Utility/Register-EngineEvent.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/Invoke-Command.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/New-PSSession.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Diagnostics/Get-Counter.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Diagnostics/Get-Counter.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Management/Restart-Computer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Management/Restart-Computer.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Disable-DscDebug.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Disable-DscDebug.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Enable-DscDebug.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Enable-DscDebug.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Get-DscConfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Get-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Restore-DscConfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Restore-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Test-DscConfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSDesiredStateConfiguration/Test-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/Invoke-Command.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-PSSession.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Diagnostics/Get-Counter.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Management/Restart-Computer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Restart-Computer.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Test-DscConfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSDesiredStateConfiguration/Test-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Diagnostics/Get-Counter.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Diagnostics/Get-Counter.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Management/Restart-Computer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Restart-Computer.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Management/Stop-Computer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Stop-Computer.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Management/Test-Connection.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Test-Connection.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/Installing-Windows-PowerShell.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Installing-Windows-PowerShell.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/Starting-the-Windows-PowerShell-2.0-Engine.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Starting-the-Windows-PowerShell-2.0-Engine.md) | :white_check_mark:Succeeded | |
[reference/mapping/monikerMapping.json](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/mapping/monikerMapping.json) | :white_check_mark:Succeeded | |

<a name="dsc%2Fdsc_roadmap.md"></a>
### [dsc/dsc_roadmap.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dsc_roadmap.md)
 - **[Warning]** Ignore metadata: ms.locale. They are generated by open publish.
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="reference%2F3.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md"></a>
### [reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F3.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md"></a>
### [reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md"></a>
### [reference/3.0/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_WorkflowCommonParameters.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md"></a>
### [reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md"></a>
### [reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md"></a>
### [reference/4.0/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/PSWorkflow/About/about_WorkflowCommonParameters.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md"></a>
### [reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md"></a>
### [reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md"></a>
### [reference/5.0/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/PSWorkflow/About/about_WorkflowCommonParameters.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs.md"></a>
### [reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FPSScheduledJob%2FAbout%2Fabout_Scheduled_Jobs_Advanced.md"></a>
### [reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSScheduledJob/About/about_Scheduled_Jobs_Advanced.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FPSWorkflow%2FAbout%2Fabout_WorkflowCommonParameters.md"></a>
### [reference/5.1/PSWorkflow/About/about_WorkflowCommonParameters.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PSWorkflow/About/about_WorkflowCommonParameters.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201709122305462004-1652%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Closing and reopening to re-trigger Appveyor build

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[dsc/dsc_roadmap.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dsc_roadmap.md) | :warning:Warning | | [Details](#user-content-dsc%2Fdsc_roadmap.md)

<a name=""></a>
### []()
 - **[Error]** System.IO.FileLoadException: Could not load file or assembly &#39;System.Composition.AttributedModel, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39; or one of its dependencies. The located assembly&#39;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: &#39;System.Composition.AttributedModel, Version=1.0.27.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&#39;
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly&amp; lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType&amp; attributeType, IRuntimeMethodInfo&amp; ctor, Boolean&amp; ctorHasParameters, Boolean&amp; isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
   at System.Composition.TypedParts.Util.DirectAttributeContext.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart&amp; part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.DocAsCode.Common.CompositionContainer.GetContainer(IEnumerable`1 assemblies)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder..ctor(IEnumerable`1 assemblies, ImmutableArray`1 postProcessorNames, String templateHash, String intermediateFolder, String commitFromSHA, String commitToSHA, Boolean cleanupCacheHistory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

 - **[Warning]** &#39;W:\adtk-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\adtk-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

<a name="dsc%2Fdsc_roadmap.md"></a>
### [dsc/dsc_roadmap.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dsc_roadmap.md)
 - **[Warning]** Ignore metadata: ms.locale. They are generated by open publish.
 - **[Warning]** Can&#39;t find output file for bread/toc.json

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201709131830369862-1652%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lgIhEPO0zfggFFL19lVjIfrIN6RlpQAbsFTWWdrsR%2FE%3D&st=2017-09-13T18%3A27%3A38Z&se=2017-09-14T18%3A37%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Close and re-open to trigger build.

**Comment by juanpablojofre** [comment]
Creating a new PR.

**Pull request closed without merging**
