### PR TITLE
Fix automation link and lint cleanup

### PR DESCRIPTION
**Pull request by DCtheGeek**
Fixed link for Azure automation service and performed minor lint cleanup.

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/azureDsc.md](https://github.com/DCtheGeek/PowerShell-Docs/blob/dmc-azurelinkfix/dsc/azureDsc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201803151601112969-2180%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wT9LcW2UQCpKe%2B0J1i%2FfqgFMKu2%2BSz%2B54Z%2F7vpklNNc%3D&st=2018-03-15T16%3A23%3A38Z&se=2018-04-15T16%3A28%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** filemap T:/20180315-164010-042b50e5/hscahfzi.nlf doesn&#39;t exist.
 - **Line 46**: **[Error]** Call W:\ytga-s\.optemp\packages\opbuild.filemappreprocessor.1.46.2\tools\Microsoft.OpenPublishing.Build.Applications.FileMapPreProcessor.exe to preprocess T:/20180315-164010-042b50e5/jju3cal3.nsr,T:/20180315-164010-042b50e5/l1pzevjy.k2u,T:/20180315-164010-042b50e5/f33wdjn5.bpg,T:/20180315-164010-042b50e5/dgtf3dko.rng,T:/20180315-164010-042b50e5/xdebbf4s.vb3,T:/20180315-164010-042b50e5/hscahfzi.nlf,T:/20180315-164010-042b50e5/tqlxaicc.4nf,T:/20180315-164010-042b50e5/c0gwfqa4.ura,T:/20180315-164010-042b50e5/fiznrzap.sio,T:/20180315-164010-042b50e5/ggzwnks4.rjv,T:/20180315-164010-042b50e5/ctya3ua1.nww,T:/20180315-164010-042b50e5/sz1tw1mn.npk,T:/20180315-164010-042b50e5/n0u43ts1.p40,T:/20180315-164010-042b50e5/rhnba1ox.ryk,T:/20180315-164010-042b50e5/42nfmaws.g33,T:/20180315-164010-042b50e5/0wmmc114.kcv,T:/20180315-164010-042b50e5/s1hogm02.jvv,T:/20180315-164010-042b50e5/opolvgj1.nk4,T:/20180315-164010-042b50e5/djf0vwez.nll failed
 - **Line 334**: **[Error]** Failed to preprocess filemaps
 - **[Warning]** Failed to restore filemap with depot name: Azure.azureps-elasticdb, locale: en-us, branch: master, details: The operation has timed out.

<a name=""></a>
### []()
 - **[Error]** filemap T:/20180315-164010-042b50e5/hscahfzi.nlf doesn&#39;t exist.
 - **Line 46**: **[Error]** Call W:\ytga-s\.optemp\packages\opbuild.filemappreprocessor.1.46.2\tools\Microsoft.OpenPublishing.Build.Applications.FileMapPreProcessor.exe to preprocess T:/20180315-164010-042b50e5/jju3cal3.nsr,T:/20180315-164010-042b50e5/l1pzevjy.k2u,T:/20180315-164010-042b50e5/f33wdjn5.bpg,T:/20180315-164010-042b50e5/dgtf3dko.rng,T:/20180315-164010-042b50e5/xdebbf4s.vb3,T:/20180315-164010-042b50e5/hscahfzi.nlf,T:/20180315-164010-042b50e5/tqlxaicc.4nf,T:/20180315-164010-042b50e5/c0gwfqa4.ura,T:/20180315-164010-042b50e5/fiznrzap.sio,T:/20180315-164010-042b50e5/ggzwnks4.rjv,T:/20180315-164010-042b50e5/ctya3ua1.nww,T:/20180315-164010-042b50e5/sz1tw1mn.npk,T:/20180315-164010-042b50e5/n0u43ts1.p40,T:/20180315-164010-042b50e5/rhnba1ox.ryk,T:/20180315-164010-042b50e5/42nfmaws.g33,T:/20180315-164010-042b50e5/0wmmc114.kcv,T:/20180315-164010-042b50e5/s1hogm02.jvv,T:/20180315-164010-042b50e5/opolvgj1.nk4,T:/20180315-164010-042b50e5/djf0vwez.nll failed
 - **Line 334**: **[Error]** Failed to preprocess filemaps
 - **[Warning]** Failed to restore filemap with depot name: Azure.azureps-elasticdb, locale: en-us, branch: master, details: The operation has timed out.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201803151639529387-2180%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=C6z66LBF71fRVYsm9kszYd1YyRU20ij4nLOwdbbE9jc%3D&st=2018-03-15T16%3A38%3A23Z&se=2018-04-15T16%3A43%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Closing and reopening to retrigger the build.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/azureDsc.md](https://github.com/DCtheGeek/PowerShell-Docs/blob/dmc-azurelinkfix/dsc/azureDsc.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201803151650353471-2180%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mrLK%2BfeTG0VwhGm5dxxSfu0JDp0xBAdwD28JXnObR9c%3D&st=2018-03-15T17%3A14%3A52Z&se=2018-04-15T17%3A19%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
