### PR TITLE
Sync back changes in Live to Staging

### PR DESCRIPTION
**Pull request by juanpablojofre**

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/powershell-6/Pester/Context.md](https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/powershell-6/Pester/Context.md) | :x:Error | | [Details](#user-content-reference%2Fpowershell-6%2FPester%2FContext.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2Fpowershell-6%2FPester%2FContext.md"></a>
### [reference/powershell-6/Pester/Context.md](https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/powershell-6/Pester/Context.md)
 - **[Error]** Unable to load file: powershell-6/Pester/Context.md via processor: AzureCliDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** :89:(106) &#39;[Describe
It
BeforeEach
AfterEach
about_Should...&#39;
 Expect hyperlink, but got [Describe It BeforeEach AfterEach about_Should about_Mocking about_TestDrive]()
 - **[Warning]** &#39;W:\na5h-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\na5h-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708141744051795-1568%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Reopened to trigger validations.

**Comment by juanpablojofre** [comment]
closing until Sanketh's PR completes.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/powershell-6/Pester/Context.md](https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/powershell-6/Pester/Context.md) | :x:Error | | [Details](#user-content-reference%2Fpowershell-6%2FPester%2FContext.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2Fpowershell-6%2FPester%2FContext.md"></a>
### [reference/powershell-6/Pester/Context.md](https://github.com/PowerShell/PowerShell-Docs/blob/live/reference/powershell-6/Pester/Context.md)
 - **[Error]** Unable to load file: powershell-6/Pester/Context.md via processor: AzureCliDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** :89:(106) &#39;[Describe
It
BeforeEach
AfterEach
about_Should...&#39;
 Expect hyperlink, but got [Describe It BeforeEach AfterEach about_Should about_Mocking about_TestDrive]()
 - **[Warning]** &#39;W:\5wk2-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\5wk2-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708141829446313-1568%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
