### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by DAXaholic**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705161302555635-1211%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@DAXaholic,
Is the typo only in the 5.1 version of the about_WQL topic?
Or it applies to all versions.
If the later is the case, can you update all versions?
Best regards,
-- JP

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/6/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/6/About/about_WQL.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705170436296988-1211%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/6/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/6/About/about_WQL.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705170438071680-1211%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_WQL.md) | :white_check_mark:Succeeded | |
[reference/6/About/about_WQL.md](https://github.com/DAXaholic/PowerShell-Docs/blob/patch-1/reference/6/About/about_WQL.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705170445341704-1211%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DAXaholic** [comment]
@juanpablojofre
Done

**Comment by zjalexander** [comment]
thank you!!

**Pull request merged**
