### PR TITLE
Replaced pipe character

### PR DESCRIPTION
**Pull request by JeffWouters**
Using the pipe messes up the table view for that row.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershell-docs/501)

### CODE REVIEW

**Comment by vors** [comment]
It's an Open Publishing System bug.

Here is OPS output:

image


Here is GitHub rendere version

image

**Comment by JeffWouters** [comment]
Ok, thanks (also for the fast response).

Jeff. 

Sergei Vorobev schreef op 11-07-2016 07:41: 

> It's an Open Publishing System bug. 
> 
> Here is OPS output: 
> 
> [1] 
> 
> Here is GitHub rendere version 
> 
> [2] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].
 

Links:
------
[1]
https://cloud.githubusercontent.com/assets/816680/16720857/5589cfc4-46ef-11e6-9a58-d2afb61409e0.png
[2]
https://cloud.githubusercontent.com/assets/816680/16720862/638da7b2-46ef-11e6-9741-96937f0e8865.png
[3]
https://github.com/PowerShell/PowerShell-Docs/pull/501#issuecomment-231646588
[4]
https://github.com/notifications/unsubscribe/AGP3ospEu4gE5G3xirw7ppV90XTsEj8Fks5qUdeCgaJpZM4JJC0c

**Comment by vors** [comment]
Well, I'm not managing this repo :) 
Just adding more details for people who are.

**Comment by HemantMahawar** [comment]
Opened an issue for this #503.
This pull request didn't addressed it correctly (at least from GitHub view) and #502 fixed it.

**Pull request closed without merging**
