### PR TITLE
Update Push-Location.md

### PR DESCRIPTION
**Pull request by rdtechie**
Added some more clarification and examples.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Management/Push-Location.md](https://github.com/rdtechie/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Management/Push-Location.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611220958414636-856%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@rdtechie  Thanks for your contribution. We would like some additional changes to your PR:
- Keep the [semantic line feeds](http://rhodesmill.org/brandon/2012/one-sentence-per-line/) so that `git diff` is easy to read, i.e: don't merge sentences on separate line into a paragraph
- If applicable, update the content for older version ([3.0](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Get-Location.md), [4.0](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Management/Get-Location.md ), [5.0](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Management/Get-Location.md )) of the documentation as well

**Comment by HemantMahawar** [comment]
@juanpablojofre  Are you planning to address the feedback (above)?

**Comment by rdtechie** [comment]
Sorry @HemantMahawar , I missed your comment somehow. I'm trying to understand the article you referenced to. My apologies for being a n00b. (-:

**Pull request merged**
