### PR TITLE
Fixing first sample in Invoke-RestMethod

### PR DESCRIPTION
**Pull request by juanpablojofre**
All versions updated

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C29%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611292202571388-868%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by joeyaiello** [comment]
Closing and reopening to retrigger timed-out CI.

Also, it might be worthwhile to get rid of the 5.0 stuff (leaving 5.1) now that we're plastering over it. Would reduce some of the time spent in CI.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C30%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611302137088984-868%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by joeyaiello** [comment]
Looks like a legitimate failure in `PSWorkflowUtility`. Can we get this fixed in staging via another branch, and then rebase this one to get us back in a stable state. We should not be making a habit of merging PRs w/ failed CI, even if the failures are unrelated to changes you made in this PR

**Comment by HemantMahawar** [comment]
@joeyaiello @juanpablojofre The errors are indeed in Invoke-RestMethod.md file. Take a look at appveyor logs.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/3.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/4.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/5.0/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-issue-867/reference/5.1/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612071908113961-868%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
