### PR TITLE
Address feedback on new escape characters.

### PR DESCRIPTION
**Pull request by rkeithhill**
This PR is tied to the acceptance of the PR https://github.com/PowerShell/PowerShell/pull/3958.

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [X] The documented feature will be introduced in version 6.0 Beta4 (hopefully - waiting on PR that implements this feature to be accepted) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/About/about_Escape_Characters.md](https://github.com/rkeithhill/PowerShell-Docs/blob/rkeithhill/update-unicode-esc-documentation/reference/6/About/about_Escape_Characters.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FAbout%2Fabout_Escape_Characters.md)
[reference/6/About/about_Special_Characters.md](https://github.com/rkeithhill/PowerShell-Docs/blob/rkeithhill/update-unicode-esc-documentation/reference/6/About/about_Special_Characters.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FAbout%2Fabout_Special_Characters.md)

<a name="reference%2F6%2FAbout%2Fabout_Escape_Characters.md"></a>
### [reference/6/About/about_Escape_Characters.md](https://github.com/rkeithhill/PowerShell-Docs/blob/rkeithhill/update-unicode-esc-documentation/reference/6/About/about_Escape_Characters.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FAbout%2Fabout_Special_Characters.md"></a>
### [reference/6/About/about_Special_Characters.md](https://github.com/rkeithhill/PowerShell-Docs/blob/rkeithhill/update-unicode-esc-documentation/reference/6/About/about_Special_Characters.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C28%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706280526440754-1414%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@rkeithhill, 
Thanks for your contribution.
One thing to ask before merging into Staging.
Would you please escape those back-ticks? 
It's making markdown go crazy assuming inline code text. 
Thanks again,
-- JP

**Comment by juanpablojofre** [comment]
@rkeithhill ,
Forget my initial comment.
Double checked and it is rendering perfect.
Thanks again,
-- JP

**Comment by rkeithhill** [comment]
@juanpablojofre No problem.  However I do think there is a small problem with `about_Special_Characters.md` file (that was there before I made my changes).  Check this out:

image

Notice how the first escape char for NULL is quite big but renders correctly as markdown.  But then the following ALERT / BACKSPACE / et. al do not.  I suggest that we think about demoting the NULL to an H2 `##` (or maybe even H3) and do that for the rest of the esc sequences.  It will look like this in VSCode:

image

That is using `###` (H3).  What do you think?  If you want me to make the change, I'd be happy to but will have to wait until tonight.

**Comment by rkeithhill** [comment]
@juanpablojofre In general, a lot of the backticks in `about_Special_Characters` have problems rendering in markdown **unless** they're in text following a `###` or in a triple backtick section.  What would be **trick** is if the markdown file was processed down to the corresponding text file and that processing removed lines with triple backticks.  That would allow the markdown to look great and then you wouldn't have that extra triple backtick baggage in the text file versions.

**Pull request merged**
