### PR TITLE
Add link to Format.ps1xml schema reference

### PR DESCRIPTION
**Pull request by felixfbecker**
I've always found myself looking up the schema reference for specifics, but it is very hard to find. This should help with that.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### CODE REVIEW

**Comment by felixfbecker** [comment]
Btw, is there a schema for Types.ps1xml files?

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-3.0&branch=pr-en-us-2892) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-4.0&branch=pr-en-us-2892) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.0&branch=pr-en-us-2892) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.1&branch=pr-en-us-2892) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6&branch=pr-en-us-2892) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 403**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201809091427225906-2892%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=V0FmfXyaS1RhCNjdQtdV0o4ytwuLJbFYM3QvKyaoUSM%3D&st=2018-09-09T14%3A46%3A37Z&se=2018-10-10T14%3A51%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by felixfbecker** [comment]
Not sure why these links are invalid. Should I use an absolute link to docs.microsoft.com/... instead?

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-3.0&branch=pr-en-us-2892) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-4.0&branch=pr-en-us-2892) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.0&branch=pr-en-us-2892) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.1&branch=pr-en-us-2892) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6&branch=pr-en-us-2892) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.
 - **Line 404**: **[Warning]** Invalid file link:(~/../developer/format/format-schema-xml-reference.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201809101525197705-2892%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XPEMxZWeoaz%2BOGdIDOIj1s7ayUfHbIEzobjmM5j6WEM%3D&st=2018-09-10T15%3A35%3A30Z&se=2018-10-11T15%3A40%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-3.0&branch=pr-en-us-2892) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-4.0&branch=pr-en-us-2892) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.0&branch=pr-en-us-2892) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-5.1&branch=pr-en-us-2892) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_format.ps1xml?view=powershell-6&branch=pr-en-us-2892) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Format.ps1xml.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md](https://github.com/felixfbecker/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/About/about_Format.ps1xml.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201809101527439606-2892%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=s9gyseZvzwiCR%2FgEU4f%2F%2Fh2Iryl8iaR8NsjBhSV1vMM%3D&st=2018-09-10T15%3A49%3A54Z&se=2018-10-11T15%3A54%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
