### PR TITLE
Fix help topic on recipient of delivery notification

### LINKED ISSUE #2880: Send-MailMessage cmdlet: Delivery Notification parameter return address is From and not To
Issue Details
-----------------
See comment by Chaitu_a in https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Send-MailMessage?view=powershell-5.1

The delivery notification should be returned to the sender and not the original addressee. Therefore the current explanation of the Delivery Notification parameter in Send-MailMessage cmdlet is explained wrong.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document (No documentation yet)
- [ ] Impacts 6.0 document (No documentation yet)
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

### PR DESCRIPTION
**Pull request by ThreeFive-O**
Fixes #2880

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [x] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/ThreeFive-O/PowerShell-Docs/blob/Fix2880/reference/3.0/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-3.0&branch=pr-en-us-2887) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/ThreeFive-O/PowerShell-Docs/blob/Fix2880/reference/4.0/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-4.0&branch=pr-en-us-2887) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/ThreeFive-O/PowerShell-Docs/blob/Fix2880/reference/5.0/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-5.0&branch=pr-en-us-2887) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md](https://github.com/ThreeFive-O/PowerShell-Docs/blob/Fix2880/reference/5.1/Microsoft.PowerShell.Utility/Send-MailMessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/send-mailmessage?view=powershell-5.1&branch=pr-en-us-2887) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201809061921184854-2887%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YsvvHKQbuS%2FBP2UNC5aTPU8%2BdRmo2%2B5yd0KBjrm0lds%3D&st=2018-09-06T19%3A31%3A01Z&se=2018-10-07T19%3A36%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by robdy** [comment]
@ThreeFive-O you might also add `Fixes #2880` so that the issue is closed automatically :)

**Comment by DCtheGeek** [comment]
For more info on what @robdy is mentioning, see [Closing issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/).

**Comment by ThreeFive-O** [comment]
@robdy Good catch, thx

**Pull request merged**
