### PR TITLE
Updated JEA paramters in cmdlet help

### PR DESCRIPTION
**Pull request by rpsqrd**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/rpsqrd/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/rpsqrd/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612061808532891-882%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@rpsqrd Does any of these 2 changes need to be made for older version (reference/3.0, reference/4.0 and reference/5.1) of cmdlet help?

**Comment by rpsqrd** [comment]
@HemantMahawar only 5.0, if we're still maintaining those docs. These parameters weren't around for 4.0/3.0.

**Comment by HemantMahawar** [comment]
@rpsqrd  We will close shortly on if 5.0 docs are maintained or not. If not maintained, they should be removed from the repo (and shouldn't be built as part of PRs) cc @juanpablojofre @joeyaiello 

In the meantime, can you make the changes for 5.0 docs as well as part of this PR?

**Comment by rpsqrd** [comment]
@HemantMahawar Sure thing -- just pushed an update with the relevant parameters for 5.0 and a line break fix for my 5.1 content.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/rpsqrd/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/new-psrolecapabilityfile.md](https://github.com/rpsqrd/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/new-psrolecapabilityfile.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/rpsqrd/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md](https://github.com/rpsqrd/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/New-PSSessionConfigurationFile.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612062036213990-882%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
