### PR TITLE
Fix link for Get-CimSession and New-CimSession

### PR DESCRIPTION
**Pull request by matt9ucci**
Fixed url, formatting, and minor differences in wording.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)
[dsc/lnxGettingStarted.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/dsc/lnxGettingStarted.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxGettingStarted.md)

<a name=""></a>
### []()
 - **[Error]** File:6/CimCmdlets/CimCmdlets.md not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\ovyr-log-6733695a\change-list-with-redirection.tsv.
 - **[Error]** File:../reference/6/CimCmdlets/CimCmdlets.md not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\ovyr-log-6733695a\change-list-with-redirection.tsv.
 - **[Warning]** &#39;W:\ovyr-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\ovyr-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

<a name="dsc%2FlnxGettingStarted.md"></a>
### [dsc/lnxGettingStarted.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/dsc/lnxGettingStarted.md)
 - **[Warning]** Ignore metadata: ms.locale. They are generated by open publish.
 - **[Warning]** Can&#39;t find output file for bread/toc.json

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C19%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708190251163016-1611%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Generating redirection file &#39;W:\4wvx-s\reference/virtual-directory-module/Microsoft.WSMan.Management/WSMan-Provider.md&#39; failed, exception details: The process cannot access the file &#39;W:\4wvx-s\reference\virtual-directory-module\Microsoft.WSMan.Management\WSMan-Provider.md&#39; because it is being used by another process..
 - **[Warning]** &#39;W:\4wvx-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\4wvx-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708230226230861-1611%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/lnxGettingStarted.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/dsc/lnxGettingStarted.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxGettingStarted.md)
[reference/3.0/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Get-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Get-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Restore-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Restore-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Start-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Start-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Test-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Test-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/4.0/PSDesiredStateConfiguration/Update-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/4.0/PSDesiredStateConfiguration/Update-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Disable-DscDebug.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Disable-DscDebug.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Enable-DscDebug.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Enable-DscDebug.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Get-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Get-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Get-DscLocalConfigurationManager.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Publish-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Publish-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Remove-DscConfigurationDocument.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Restore-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Restore-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Start-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Start-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Stop-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.0/PSDesiredStateConfiguration/Test-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.0/PSDesiredStateConfiguration/Test-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Disable-DscDebug.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Disable-DscDebug.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Enable-DscDebug.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Enable-DscDebug.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Get-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Get-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Get-DscConfigurationStatus.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Publish-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Publish-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Set-DscLocalConfigurationManager.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Start-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Start-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Test-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Test-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/5.1/PSDesiredStateConfiguration/Update-DscConfiguration.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/5.1/PSDesiredStateConfiguration/Update-DscConfiguration.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/CimCmdlets.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/CimCmdlets.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/Get-CimClass.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/Get-CimClass.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/Get-CimSession.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/Get-CimSession.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/Invoke-CimMethod.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/Invoke-CimMethod.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/New-CimSession.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/New-CimSession.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/New-CimSessionOption.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/New-CimSessionOption.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/Register-CimIndicationEvent.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/Register-CimIndicationEvent.md) | :white_check_mark:Succeeded | |
[reference/6/CimCmdlets/Remove-CimSession.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/CimCmdlets/Remove-CimSession.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Import-Module.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Import-Module.md) | :white_check_mark:Succeeded | |

<a name="dsc%2FlnxGettingStarted.md"></a>
### [dsc/lnxGettingStarted.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-1/dsc/lnxGettingStarted.md)
 - **[Warning]** Ignore metadata: ms.locale. They are generated by open publish.
 - **[Warning]** Can&#39;t find output file for bread/toc.json

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708231028322826-1611%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Thanks Matt !! @matt9ucci

**Pull request merged**
