### PR TITLE
Azure blob automation

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Infrastructure work for automation

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702070325507170-1014%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by adityapatwardhan** [comment]
This PR is not ready to merge yet.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702072002453801-1014%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702072152319007-1014%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702072217125155-1014%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702080123192367-1014%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
