### PR TITLE
Updated Win7/Srv2008R2 instructions for WMF5.1 installation

### PR DESCRIPTION
**Pull request by kursatari**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C19%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701190605350149-967%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
Waiting for @JKeithB

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C19%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701191810178680-967%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
Had an offline chat with @JKeithB . This is work in progress and not ready to publish yet.

**Pull request closed without merging**
