### PR TITLE
Update DSC-improvements.md

### PR DESCRIPTION
**Pull request by doctordns**
1. Tidied up incorrect English grammar.
2. Changed 'customer', 'user' to you to simplify the text.
3. Removed future tense - future tense is both harder for some non-English native speakers to understand and is harder for localization.
Minor changes to improve an already great article.

Version(s) of document impacted
------------------------------
- [X ] Impacts 5.1 document
- [X ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/DSC-improvements.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-10/wmf/5.1/DSC-improvements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704181557078079-1160%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ArieHein** [comment]
line 44, ends with:
"By default CircularLogging is be set to TRUE. "   - remove 'be' from it.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/DSC-improvements.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-10/wmf/5.1/DSC-improvements.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C20%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704201611445331-1160%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
thank you!! :)

**Pull request merged**
