### PR TITLE
Publishing latest changes to Live

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md)
[STYLE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |
[wmf/5.1/install-configure.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.1/install-configure.md) | :white_check_mark:Succeeded | |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201711021738536546-1827%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=93jcI6%2FVQdzg7on7QRVjOC1B0cxYWshQH5eUsVI1Xh8%3D&st=2017-11-02T18%3A05%3A21Z&se=2017-12-03T18%3A10%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Closing and reopening to re-trigger build.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md)
[STYLE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md) | :white_check_mark:Succeeded | |
[appveyor.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/appveyor.yml) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |
[wmf/5.1/install-configure.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.1/install-configure.md) | :white_check_mark:Succeeded | |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201711022007269199-1827%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NojQQndHhHcI2CUtCRJzRDcVseeWGXkd1DoclwVp%2F1o%3D&st=2017-11-02T20%3A32%3A14Z&se=2017-12-03T20%3A37%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by joeyaiello** [comment]
LGTM! We did it! ;)

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md)
[STYLE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md) | :white_check_mark:Succeeded | |
[appveyor.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/appveyor.yml) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |
[wmf/5.1/install-configure.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.1/install-configure.md) | :white_check_mark:Succeeded | |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201711022008092836-1827%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2eAzqc6ZqUUTz5wOS6wKbj%2FmuKUN5SP8u7iBPvPfnRQ%3D&st=2017-11-02T21%3A06%3A21Z&se=2017-12-03T21%3A11%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
