### PR TITLE
Update New-PSRoleCapabilityFile.md

### PR DESCRIPTION
**Pull request by athaynes**
Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [x] The documented feature was introduced in version (list version here) of PowerShell
- [x] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704071303245642-1143%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
Thanks for the fix. Would you be able to make this fix for the 5.0 and 6.0 versions as well? If not, please create a new issue tracking the need to update those versions as well.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704080524311759-1143%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/Microsoft.PowerShell.Core/new-psrolecapabilityfile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/new-psrolecapabilityfile.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704080526550533-1143%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by athaynes** [comment]
@zjalexander I updated 5.0 and 6.0 as well.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md](https://github.com/athaynes/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/New-PSRoleCapabilityFile.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704080524311759-1143%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
thank you!

**Pull request merged**
