### PR TITLE
Removed broken link

### PR DESCRIPTION
**Pull request by BernieWhite**
Removed broken link to https://msdn.microsoft.com/en-us/powershell/wmf/dsc_runas.

Correct WMF 5.0 release notes page redirects to "Running DSC with user credentials" which is referenced a few paragraphs above.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/configDataCredentials.md](https://github.com/BernieWhite/PowerShell-Docs/blob/BernieWhite-patch-2/dsc/configDataCredentials.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201703062324176273-1084%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by GavinEke** [comment]
Another option is to update the link to its new location https://msdn.microsoft.com/en-us/powershell/dsc/runasuser

**Comment by BernieWhite** [comment]
@GavinEke Happy to add additional link to https://msdn.microsoft.com/en-us/powershell/dsc/runasuser if that is the preferred option.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/configDataCredentials.md](https://github.com/BernieWhite/PowerShell-Docs/blob/BernieWhite-patch-2/dsc/configDataCredentials.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201703072039427327-1084%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/configDataCredentials.md](https://github.com/BernieWhite/PowerShell-Docs/blob/BernieWhite-patch-2/dsc/configDataCredentials.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201703072041264105-1084%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eslesar** [comment]
@BernieWhite Thank you for this contribution. I added the link to the runAsUser topic to your PR.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/configDataCredentials.md](https://github.com/BernieWhite/PowerShell-Docs/blob/BernieWhite-patch-2/dsc/configDataCredentials.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201703072044152907-1084%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
