### PR TITLE
Jkeithb fixes08

### PR DESCRIPTION
**Pull request by JKeithB**
Updating the PSGallery publishing guidelines with info on testing to a local repo.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/JKeithB/PowerShell-Docs/blob/jkeithbFixes08/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708100118395977-1551%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Closing and reopening to see if this makes Appveyor to succeed.

**Comment by juanpablojofre** [comment]
Reopening to trigger validations.

**Comment by juanpablojofre** [comment]
@zjalexander,

Could you ask someone, from the build automation team, to review why this PR is failing with Appveyor?
Thanks in advance.

@JKeithB,
I have requested help to understand why is your PR failing in the build validation. 
Thanks for your patience.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/JKeithB/PowerShell-Docs/blob/jkeithbFixes08/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708101703557316-1551%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/JKeithB/PowerShell-Docs/blob/jkeithbFixes08/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708101711066609-1551%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by joeyaiello** [comment]
I'm dealing w/ some other issues today on this repo, but we can sync offline @JKeithB so I can sort you out. Not sure what the problem is, but if there's a critical timeline here, let me know.

**Comment by joeyaiello** [comment]
So now Appveyor is not even showing a check at all....

@juanpablojofre have you seen this before?

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/JKeithB/PowerShell-Docs/blob/jkeithbFixes08/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708102112258495-1551%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/JKeithB/PowerShell-Docs/blob/jkeithbFixes08/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708102117246755-1551%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
