### PR TITLE
Updating wmf5.1 product incompatibility

### PR DESCRIPTION
**Pull request by juanpablojofre**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/productincompat.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-wmf51patch1/wmf/5.1/productincompat.md) | :white_check_mark:Succeeded | |
[wmf/TOC.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-wmf51patch1/wmf/TOC.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201703141835124934-1093%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
Addresses #1092

**Comment by HemantMahawar** [comment]
@zjalexander Should this content go under https://msdn.microsoft.com/en-us/powershell/wmf/5.1/compatibility ? The current content in there is covered @ https://msdn.microsoft.com/en-us/powershell/wmf/readme

**Comment by mgreenegit** [comment]
@HemantMahawar I think the important thing is consistency across the two versions.
Also, I just noticed there is an additional comment on Exchange (heads up @juanpablojofre)
https://twitter.com/no_identd/status/841613708463869956

**Pull request merged**
