### PR TITLE
Fixing PowerShell\PowerShell-Docs Issue #1051

### PR DESCRIPTION
**Pull request by kiazhi**
This is an attempt to address formatting issue of about_Comparison_Operators.md for 3.0, 4.0, 5.0 and 5.1 .

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702150158296459-1053%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by nzubair** [comment]
The bitwise operators section is pretty messed up. I think it's the table causing the problems. Since the limitation of markdown tables is no row-spanning. You can't use three backtick syntax. You have to use the inline code block. 

May be something like this would be more suitable:

```
|Operator|Description|Example|
|--------|----------------------|-------------------|
|-band|Bitwise AND|`PS C:> 10 -band 3`<br />`2`|
|-bor|Bitwise OR (inclusive)|`PS C:> 10 -bor 3`<br />`11`|
|-bxor|Bitwise OR (exclusive)|`PS C:> 10 -bxor 3`<br />`9`|
|-bnot|Bitwise NOT|`PS C:> -bNot 10`<br />`-11`|
|-shl|Shift-left|`PS C:> 100 -shl 2`<br />`400`|
|-shr|Shift-right|`PS C:> 100 -shr 1`<br />`50`|
```
Which will render like this:

|Operator|Description|Example|
|--------|----------------------|-------------------|
|-band|Bitwise AND|`PS C:> 10 -band 3`<br />`2`|
|-bor|Bitwise OR (inclusive)|`PS C:> 10 -bor 3`<br />`11`|
|-bxor|Bitwise OR (exclusive)|`PS C:> 10 -bxor 3`<br />`9`|
|-bnot|Bitwise NOT|`PS C:> -bNot 10`<br />`-11`|
|-shl|Shift-left|`PS C:> 100 -shl 2`<br />`400`|
|-shr|Shift-right|`PS C:> 100 -shr 1`<br />`50`|

That's what I ended up doing for [about_Arithmetic_Operators](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md)


Also, wrong sections seem to be highlighted as code. That's probably due to the messed up table.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702150242588021-1053%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by kiazhi** [comment]
@nzubair Thanks for that tips. I have updated the bitwise operator table.

**Pull request merged**
