### PR TITLE
Cmdlet help for ConvertFrom-Clixml and ConvertTo-Clixml 

### PR DESCRIPTION
**Pull request by charlieschmidt**
https://github.com/PowerShell/PowerShell/issues/3898

https://github.com/PowerShell/PowerShell/pull/5815

Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/ConvertTo-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/ConvertTo-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801090527500654-2022%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=L%2FgMCbBWWkXdHsFwZjBRYclXjk5IFAyCBPp2jipGlO0%3D&st=2018-01-09T05%3A49%3A26Z&se=2018-02-09T05%3A54%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/ConvertTo-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/ConvertTo-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801091527353771-2022%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t%2BNhR92Itd%2FuShb%2BQwvD2HZOuXg03tsqNREEVMmKYtY%3D&st=2018-01-09T15%3A49%3A48Z&se=2018-02-09T15%3A54%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/ConvertTo-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/ConvertTo-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/Export-Clixml.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md](https://github.com/charlieschmidt/PowerShell-Docs/blob/convertto-convertfrom-clixml-cmdlet-help/reference/6/Microsoft.PowerShell.Utility/Import-Clixml.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801091531344009-2022%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=O%2B77E7Zbw0kJAhM2Rt6AGxxo0ZprXyUG9YPn%2BUsi1WY%3D&st=2018-01-09T16%3A17%3A26Z&se=2018-02-09T16%3A22%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by felixfbecker** [comment]
This PR was merged, but the linked PR https://github.com/PowerShell/PowerShell/pull/5815 was never merged and actually closed because of inactivity.
These cmdlets are in the official docs now https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertfrom-clixml?view=powershell-6 but don't actually exist:
```
$ ConvertFrom-Clixml
ConvertFrom-Clixml : The term 'ConvertFrom-Clixml' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ConvertFrom-Clixml
+ ~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (ConvertFrom-Clixml:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
This is very misleading.

**Pull request merged**
