### PR TITLE
Get-Module - less horizontal scrolling

### PR DESCRIPTION
**Pull request by petervandivier**
move commentary outside code-blocks to reduce horizontal scrolling

### CODE REVIEW

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/petervandivier/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/petervandivier/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Get-Module.md)
 - **[Error]** Unable to load file: 6/Microsoft.PowerShell.Core/Get-Module.md via processor: AzureCliDocumentProcessor: :221:(1745) &#39;```powershell
PS&gt; Get-Content $m.Path
```

&#39;
 Expect Heading

<a name=""></a>
### []()
 - **[Error]** Markdown.MAML.Transformer.HelpSchemaException: :221:(1745) &#39;```powershell
PS&gt; Get-Content $m.Path
```

&#39;
 Expect Heading
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807121351166923-2681%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ljz4Uo8Wu98GyJkzu7bypCReg467WO9I7%2Bz1%2BPblUQM%3D&st=2018-07-12T13%3A55%3A10Z&se=2018-08-12T14%3A00%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/petervandivier/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FGet-Module.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/petervandivier/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Get-Module.md)
 - **[Error]** Unable to load file: 6/Microsoft.PowerShell.Core/Get-Module.md via processor: AzureCliDocumentProcessor: :222:(1745) &#39;```powershell
PS&gt; Get-Content $m.Path
```

&#39;
 Expect Heading

<a name=""></a>
### []()
 - **[Error]** Markdown.MAML.Transformer.HelpSchemaException: :222:(1745) &#39;```powershell
PS&gt; Get-Content $m.Path
```

&#39;
 Expect Heading
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807121501224344-2681%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CnmVzeqFu7bu%2Bj3mH1sBe%2BxP%2BfKg190R1NVpyxurABQ%3D&st=2018-07-12T15%3A04%3A35Z&se=2018-08-12T15%3A09%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
@petervandivier I see what the error here is now, missed it the first read through.  The MAML format only allows a code block and then a comment, but not another code block before another header is there.  That's part of why all the comments where in the code block so that there was only one code block per header and it didn't violate the MAML formatting rules.

I really like the direction of making it more readable (less scrolling)... can you find a way to do so, but only have one PS code block in each header (example) to stay within the MAML formatting rules?

**Comment by petervandivier** [comment]
🤞 this update suffices. the only other idea i had off the top of my head was to linebreak the comments within the markdown code blocks, but then it won't dynamically scale with screen size.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/petervandivier/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/get-module?view=powershell-6&branch=pr-en-us-2681) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807121559039265-2681%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gfH1zSU%2BAwhBrmOQ3zrnGvVhAM7rw%2BwHBn25KampH3A%3D&st=2018-07-12T16%3A04%3A42Z&se=2018-08-12T16%3A09%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
This looks like an acceptable compromise between usability and the MAML rules.  I'm going to have @sdwheeler take a look, too, before merging it in.

**Comment by DCtheGeek** [comment]
@petervandivier @sdwheeler and I talked about this and decided to rotate the sections a bit to be more Intro, Example(s), Explanation in layout (keeping your changes, just re-ordering them).  Really appreciate your contribution here and helping improve and streamline this content!

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Get-Module.md](https://github.com/petervandivier/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Get-Module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/get-module?view=powershell-6&branch=pr-en-us-2681) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807161545339712-2681%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=GQ3Xw3ZgpD%2FVh9MUJl5QmCgJ1ivfu8%2B0CvGChlhB%2BG0%3D&st=2018-07-16T15%3A50%3A34Z&se=2018-08-16T15%3A55%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
@petervandivier Thanks again... with the update layout, we are merging in.  Appreciate the contribution and help here!

**Pull request merged**
