### PR TITLE
Add dev owners to `reference` docset

### PR DESCRIPTION
**Pull request by joeyaiello**
Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

This is to add dev owners to the `docfx.json` for `reference` so that reference doc issue notifications are distributed throughout the team.

I'd like @SteveL-MSFT to sign off on this before we merge it in. (And before you ask: no, it doesn't look like ` docfx.json` supports multiple owners...)

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[82f7078](https://github.com/joeyaiello/PowerShell-Docs/pull/3489/commits/82f7078c5f76e5954dc57b98db8ceaec5d3d8f23)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[82f7078](https://github.com/joeyaiello/PowerShell-Docs/pull/3489/commits/82f7078c5f76e5954dc57b98db8ceaec5d3d8f23)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 22 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[82f7078](https://github.com/joeyaiello/PowerShell-Docs/pull/3489/commits/82f7078c5f76e5954dc57b98db8ceaec5d3d8f23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/3.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-3.0&branch=pr-en-us-3489) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md)
[reference/4.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/4.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-4.0&branch=pr-en-us-3489) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md)
[reference/5.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/5.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-5.0&branch=pr-en-us-3489) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md)
[reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-5.1&branch=pr-en-us-3489) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md)
[reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-6&branch=pr-en-us-3489) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md)
[reference/docfx.json](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/docfx.json) | :white_check_mark:Succeeded | |

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md"></a>
### [reference/3.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/3.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** Author TravisEz123 cannot be recognized in GitHub.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md"></a>
### [reference/4.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/4.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** Author TravisEz123 cannot be recognized in GitHub.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md"></a>
### [reference/5.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/5.0/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** Author TravisEz123 cannot be recognized in GitHub.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md"></a>
### [reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/5.1/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** Author TravisEz123 cannot be recognized in GitHub.

<a name="reference%2F6%2FMicrosoft.PowerShell.Security%2FAbout%2Fabout_Certificate_Provider.md"></a>
### [reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md](https://github.com/joeyaiello/PowerShell-Docs/blob/docsOwners/reference/6/Microsoft.PowerShell.Security/About/about_Certificate_Provider.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** Author TravisEz123 cannot be recognized in GitHub.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901022236305787-3489%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qFc2LXNvjCbSycTyGRGU518eHrOc6jlmH%2B8a7GSGi3Y%3D&st=2019-01-02T22%3A48%3A21Z&se=2019-02-02T22%3A53%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by edyoung** [comment]
lgtm

**Pull request merged**
