### PR TITLE
Update Add-Member.md example layouts

### PR DESCRIPTION
**Pull request by shanehoey**
fixed layout of examples 1,2 ,3

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Add-Member.md](https://github.com/shanehoey/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Utility/Add-Member.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801151530017753-2055%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2ldDLxhsZNUcpSxno0a7%2BNp4JHUDs7yX451cpzOZLKo%3D&st=2018-01-15T15%3A53%3A12Z&se=2018-02-15T15%3A58%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@shanehoey Thanks for the update. In order to accept your change I need you to sign the Contributor License Agreement. You only need to do this once. After that, it will be active for any future contributions you make.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Add-Member.md](https://github.com/shanehoey/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Utility/Add-Member.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801151550437966-2055%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VbdLcr%2BuuYu6%2FdzfVATPbjIWPNg10G%2F6KZs9%2Bw2RNT8%3D&st=2018-01-15T16%3A23%3A00Z&se=2018-02-15T16%3A28%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by shanehoey** [comment]
@sdwheeler Contributor License Agreement signed, thanks

**Pull request merged**
