### PR TITLE
Update Measure-Command.md to reflect StyleGuide

### PR DESCRIPTION
**Pull request by jessiewestlake**
- Change capitalization of headers/titles to sentence case
- Change highlighting of cmdlet names to use backticks instead of double-asterisks
- Format PowerShell code syntax using code highlighting
- Correct unnumbered lists' indentation and bullets

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C26%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705260855012373-1233%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@jessiewestlake,
Thanks for this contribution!!
Would you mind updating the other versions of the document or creating an issue to track the pending work item.
Thanks again,
-- JP

**Comment by zjalexander** [comment]
restarting builds

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/jessiewestlake/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706062047149751-1233%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
hey @joeyaiello can you help me understand this build error and how to remediate it?
 https://ci.appveyor.com/project/PowerShell/powershell-docs/build/1.0.636#L836

**Comment by kiazhi** [comment]
Hi @zjalexander,

Finally, got to the bottom of this. I have updated all versions on those #1278, #1279, #1280, #1281,#1282 pull requests and close this #1233 pull request.

Apparently, PlatyPS Schema checks each PowerShell code tag and expect a heading:

- **Correct Syntax 1**

\### Example Heading

\```PowerShell
Get-Command
\```

\```PowerShell
Get-Command
\```

The above example 1 is blah... And the above example 2 is blah...

- **Correct Syntax 2**

\### Example 1 Heading

\```PowerShell
Get-Command
\```

The above example 1 is blah...

\### Example 2 Heading

\```PowerShell
Get-Command
\```

The above example 2 is blah...

- **Incorrect Syntax**

\### Example Heading

\```PowerShell
Get-Command
\```

The above example 1 is blah... (It is because according to PlatyPS Schema, this below \```PowerShell code tag should have a Heading.)

\```PowerShell
Get-Command
\```

The above example 2 is blah...

**Comment by jessiewestlake** [comment]
This makes perfect sense, now that you mention it. There are several built-in examples in the documentation which feature multiple examples in a row, contained within the heading of a single example. This is in order to either explain differences between two commands, or a succession of multiple commands and their output, which end with the resulting explanation.

This is what the *measure-command.md* had already, and I did not change it. In the future, I will try to remedy the formatting problems before submitting a PR.

**Comment by joeyaiello** [comment]
Am I still needed here? Looks like you guys figured it out...

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/jessiewestlake/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md)

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md"></a>
### [reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/jessiewestlake/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Measure-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C31%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707311515241794-1233%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
