### PR TITLE
Change Get-WMIObject cmdlet reference to Get-CimInstance in Collecting-Information-About-Computers.md.

### PR DESCRIPTION
**Pull request by sethvs**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### CODE REVIEW

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 108**: **[Error]** Restore nuget package W:\aayx-s\.optemp\dependentPackages\Microsoft.OpenPublishing.CommonPlugins\packages.config in folder:W:\aayx-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error:  Errors in packages.config projects     Unable to find version &#39;1.0.120-alpha&#39; of package &#39;Microsoft.OpenPublishing.CommonPlugins&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.120-alpha&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://www.myget.org/F/op-dev/api/v2: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.120-alpha&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2&#39;.
 - **Line 290**: **[Error]** Restore dependent packages failed

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805021104137921-2386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KmI6rHvtRCdxJnfMKB74vXhFf%2B0OAvn3UHl3Vmw1xZ4%3D&st=2018-05-02T11%3A00%3A09Z&se=2018-06-02T11%3A05%3A09Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sethvs** [comment]
Hm. Should we restart tests?

**Comment by sdwheeler** [comment]
Close and reopen to retrigger the build.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/getting-started/cookbooks/Collecting-Information-About-Computers.md](https://github.com/sethvs/PowerShell-Docs/blob/WMI_CIM/reference/docs-conceptual/getting-started/cookbooks/Collecting-Information-About-Computers.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805021433382506-2386%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Lyr5BteO0wjRTi1vA%2BkHiAEsE0O%2BStnKdc%2FS2XPEZAk%3D&st=2018-05-02T14%3A38%3A39Z&se=2018-06-02T14%3A43%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
