### PR TITLE
Updated about_Classes to fix issue #2872

### PR DESCRIPTION
**Pull request by sdwheeler**
Added information about interfaces. Did an acrolinx editorial pass.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [x] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_classes?view=powershell-5.0&branch=pr-en-us-2873) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_classes.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_classes?view=powershell-5.1&branch=pr-en-us-2873) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/6/Microsoft.PowerShell.Core/About/about_Classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_classes?view=powershell-6&branch=pr-en-us-2873) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md)

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_classes.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/6/Microsoft.PowerShell.Core/About/about_Classes.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C31%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808311713591793-2873%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0lkuncqIaTjiQkNCx%2FT9JKMt9569GSkqyifig3njDAU%3D&st=2018-08-31T17%3A25%3A03Z&se=2018-10-01T17%3A30%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
#sign-off
Acrolinx 80/91

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_classes?view=powershell-5.0&branch=pr-en-us-2873) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_classes.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_classes?view=powershell-5.1&branch=pr-en-us-2873) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/6/Microsoft.PowerShell.Core/About/about_Classes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_classes?view=powershell-6&branch=pr-en-us-2873) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md)
[contributing/3-STYLE-GUIDE.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/contributing/3-STYLE-GUIDE.md) | :white_check_mark:Succeeded | |

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_classes.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.0/Microsoft.PowerShell.Core/About/about_classes.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/5.1/Microsoft.PowerShell.Core/About/about_Classes.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Classes.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Classes.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2872/reference/6/Microsoft.PowerShell.Core/About/about_Classes.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C31%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808311742026075-2873%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dHgV2%2B%2BARfRDZeqXL%2B0%2BbVpuQhuE%2FckAaWT0C%2FpotQ0%3D&st=2018-08-31T17%3A53%3A39Z&se=2018-10-01T17%3A58%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@DCtheGeek Still LGTM ;-)

**Pull request merged**
