### PR TITLE
Fix platyPS schema problems in reference/ folder

### PR DESCRIPTION
**Pull request by vors**
This is a second part of #798

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Get-Culture.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/4.0/Microsoft.PowerShell.Utility/Get-Culture.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/4.0/Microsoft.PowerShell.Utility/Get-Culture.md)
[reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md)
[reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md)
[reference/5.0/Microsoft.PowerShell.Utility/Get-Culture.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Utility/Get-Culture.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Utility/Get-Culture.md)
[reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md)
[reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md)
[reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md)
[reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md)









For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611160049427907-812%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Get-Culture.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/4.0/Microsoft.PowerShell.Utility/Get-Culture.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/4.0/Microsoft.PowerShell.Utility/Get-Culture.md)
[reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md)
[reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-String.md)
[reference/5.0/Microsoft.PowerShell.Utility/Get-Culture.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Utility/Get-Culture.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Utility/Get-Culture.md)
[reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.0/Microsoft.PowerShell.Utility/Get-Runspace.md)
[reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.1/Microsoft.PowerShell.Core/Register-ArgumentCompleter.md)
[reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-String.md)
[reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md](https://github.com/vors/PowerShell-Docs/blob/platyps/reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.1/Microsoft.PowerShell.Utility/Get-Culture.md)









For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611160103586825-812%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@vors !
Hi Sergei,
I'm not quite convinced of your edits to ConvertFrom-String reference topic.
Can you explain why you removed the samples written in PowerShell language and replaced with output only content?

**Comment by juanpablojofre** [comment]
@vors 
Sergei, your changes didn't touch 5.1 reference content...
Which leaves the documentation in an odd state.

**Comment by vors** [comment]
Hi @juanpablojofre 

1) PlatyPS schema at the moment doesn't support more then 1 scriptblock in the example, so it has to be concatenated, if you want to produce maml.
2) It redundant because PS code is duplicated in the first snippet and then after `C:\>` in the second snippet. I.e.
image

Why do we need `"Hello World" | ConvertFrom-String` twice?

I should admit that even with my changes `ConvertFrom-String.md` still doesn't build, because of https://github.com/PowerShell/platyPS/issues/239

If you'd like, I can separate changes to ConvertFrom-String.md into a separate PR and we can merge the rest of them. That way we can discuss this changes and not block other changes.

**Comment by vors** [comment]
I opened 2 separate PRs for these changes.

**Pull request closed without merging**
