### PR TITLE
C59287: Removing "> "

### PR DESCRIPTION
**Pull request by v-makoud**
Hello, @bobbytreed,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[171b20b](https://github.com/v-makoud/PowerShell-Docs/pull/3516/commits/171b20b671270dde327226dcbf19147495b9c45c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[171b20b](https://github.com/v-makoud/PowerShell-Docs/pull/3516/commits/171b20b671270dde327226dcbf19147495b9c45c)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 20 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[171b20b](https://github.com/v-makoud/PowerShell-Docs/pull/3516/commits/171b20b671270dde327226dcbf19147495b9c45c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/tutorials/bootstrapDsc.md](https://github.com/v-makoud/PowerShell-Docs/blob/patch-5/dsc/tutorials/bootstrapDsc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/dsc/tutorials/bootstrapdsc?branch=pr-en-us-3516) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901081350329654-3516%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5t07%2BonYDWMQuJQRbhOD06YUhEJHPvt1DoL%2FpR5a8ig%3D&st=2019-01-08T13%3A59%3A39Z&se=2019-02-08T14%3A04%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@v-makoud I didn't realize that this change was targeted at the live branch.

In the future, DO NOT submit changes to the live branch. You much make the change to the staging branch. Changes to staging will be merged to the live branch. That is the correct workflow.

**Pull request merged**
