### PR TITLE
Updated Style.md

### PR DESCRIPTION
**Pull request by kiazhi**
Correcting "C:\ PS>" to "PS C:\>" & added some correct or incorrect examples

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[STYLE.md](https://github.com/kiazhi/PowerShell-Docs/blob/patch-6/STYLE.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706121120164456-1283%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
thank you!

**Comment by juanpablojofre** [comment]
@zjalexander,
Please review this PR and let us know your opinion on these chenges.
I'm not sure that removing _When writing an article (as opposed to reference content), the first instance of a cmdlet name should be a link to the cmdlet documentation _ is the correct thing to do.

I strongly believe that articles should use links for the first mention of a cmdlet. So, the reader has an option to get illustrated about the cmdlet; in case is the first time, for the reader, that comes across the mentioned cmdlet.

**Comment by zjalexander** [comment]
that guidance didn't get removed, just moved to be more consistent with other example phrasings

**Pull request merged**
