### PR TITLE
Update Get-WinEvent.md

### PR DESCRIPTION
**Pull request by doctordns**
Removed future tense in a couple of places to improve readability. Minor edit.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md](https://github.com/doctordns/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Diagnostics/Get-WinEvent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.diagnostics/get-winevent?view=powershell-5.1&branch=pr-en-us-2761) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808021158516115-2761%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AoFdnQrsEWt6ji8%2FagZkZTdvaZQfhOR9gt%2FrzKF5mi0%3D&st=2018-08-02T12%3A08%3A47Z&se=2018-09-02T12%3A13%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by doctordns** [comment]
The changes are made but as separate PRs. 

Still not quite sure how to edit multiple docs for a single PR from the GitHub GUI.

**Comment by sdwheeler** [comment]
@doctordns You can't do multiple files in the GitHub UI. You have to use git and work in a clone of your fork.

**Comment by doctordns** [comment]
Ahh. 
I've been without my main desktop system this week - and there was not enough space on my laptop to close the repo. :-)  I'll try harder next time! ;-)

**Pull request merged**
