### PR TITLE
Closes #3345 and Closes #3428 - about_Execution_Policies

### LINKED ISSUE #3345: No mention of Windows 10 or later Server versions
This document mentions the default for Windows 8 / Server 2012 but not later releases. I think it should be either updated for the latest or remove the info about Windows 8.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b625828f-e35f-25e6-698f-1469d4817d6f
* Version Independent ID: cfa0b0d5-be1f-b9d2-533d-61bfa6051292
* Content: [about_Execution_Policies](https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1)
* Content Source: [reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

### LINKED ISSUE #3428: Execution policy on UNIX-like platforms undocumented
We should document the execution policy behaviour of PowerShell on UNIX-like platforms

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4745d24-83a7-d977-051a-c5a46123cdcd
* Version Independent ID: cfa0b0d5-be1f-b9d2-533d-61bfa6051292
* Content: [About Execution Policies](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

### PR DESCRIPTION
**Pull request by davidsmatlak**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Acrolinx score
Original version: 78
Updated version: 80

- Applied Style changes
- Minor copyedits
- Fixed broken link in 3.0 - 5.1 documents

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[bf4ffca](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/bf4ffca63a1329117dd0a4497e3e999b221f0a49)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 19 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[bf4ffca](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/bf4ffca63a1329117dd0a4497e3e999b221f0a49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-3.0&branch=pr-en-us-3548) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-4.0&branch=pr-en-us-3548) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.0&branch=pr-en-us-3548) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1&branch=pr-en-us-3548) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6&branch=pr-en-us-3548) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901142028599020-3548%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Z2AZBezCHcxHKnqzv3dDHjvyrxRytzFpdXikvXwd6Fs%3D&st=2019-01-14T20%3A39%3A44Z&se=2019-02-14T20%3A44%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidsmatlak** [comment]
Updated the documents:

- Reflowed paragraphs
- Fixed list indents and line spacing
- Inserted blank lines between blocks
- Minor copyedits

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[27be09b](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/27be09bff1b26fd9c991c04d834c973bff4aa1e6)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[27be09b](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/27be09bff1b26fd9c991c04d834c973bff4aa1e6)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 19 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[27be09b](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/27be09bff1b26fd9c991c04d834c973bff4aa1e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-3.0&branch=pr-en-us-3548) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-4.0&branch=pr-en-us-3548) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.0&branch=pr-en-us-3548) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1&branch=pr-en-us-3548) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6&branch=pr-en-us-3548) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901151633563521-3548%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2ZdwhYCl0ZJRJYBwe0d%2BJlO%2BRCAKeamMdvwHmpZkxvQ%3D&st=2019-01-15T16%3A43%3A00Z&se=2019-02-15T16%3A48%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d4ed637](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/d4ed6374a13d645f2be83b381769b35cce7a53e5)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d4ed637](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/d4ed6374a13d645f2be83b381769b35cce7a53e5)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 18 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[d4ed637](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/d4ed6374a13d645f2be83b381769b35cce7a53e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-3.0&branch=pr-en-us-3548) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-4.0&branch=pr-en-us-3548) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.0&branch=pr-en-us-3548) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-5.1&branch=pr-en-us-3548) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6&branch=pr-en-us-3548) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/3.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/4.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.0/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/5.1/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Execution_Policies.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-issue3345-3428/reference/6/Microsoft.PowerShell.Core/About/about_Execution_Policies.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: locale. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901151654049740-3548%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kwOFZYOfmrAU21AJRYw%2BawghkQVBHIhW7%2FpRfz5LGSM%3D&st=2019-01-15T17%3A04%3A53Z&se=2019-02-15T17%3A09%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[6441cae](https://github.com/davidsmatlak/PowerShell-Docs/pull/3548/commits/6441cae39f62bf9529f006ad10b6be6c21fa388b)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Pull request merged**
