### PR TITLE
Updating Live with latest About_* topics fixes

### PR DESCRIPTION
**Pull request by juanpablojofre**

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md)
[STYLE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710262116273001-1814%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oH748Cs9Tp%2FhZSmFWwDX8VKzJhNj9tlqnfQLhNJczyI%3D&st=2017-10-26T21%3A41%3A28Z&se=2017-11-26T21%3A46%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
close and reopen to trigger apveyor build

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md)
[STYLE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C27%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710271728574553-1814%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7Qlki%2B41KsIRV6RQN4DeWxWhnc%2FuZko4aYqJKVkW1yA%3D&st=2017-10-27T17%3A54%3A23Z&se=2017-11-27T17%3A59%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
close and reopen to trigger apveyor build

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md)
[STYLE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C31%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710312048405569-1814%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JgjS3Jtshfi08rAJWaMzFnmrCD0I0uMG8%2Bctc8DPfZA%3D&st=2017-10-31T21%3A14%3A48Z&se=2017-12-01T21%3A19%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md)
[STYLE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/STYLE.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |
[wmf/5.1/install-configure.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.1/install-configure.md) | :white_check_mark:Succeeded | |

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Automatic_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Automatic_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Environment_Variables.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Environment_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Wildcards.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Wildcards.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C1%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201711011350442767-1814%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BIb%2Fvecdh3jOE9cST8vPzU01j7nMsPtWSFx%2F7BzpiwA%3D&st=2017-11-01T14%3A15%3A12Z&se=2017-12-02T14%3A20%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Closing this broken PR. Will create a new PR for live.

**Pull request closed without merging**
