### PR TITLE
Remove numerous extraneous backslash characters

### PR DESCRIPTION
**Pull request by geeeyetee**
Replaced 180 instances of "\$" with "$", reverting all affected variable mentions to their state from before commit https://github.com/PowerShell/PowerShell-Docs/commit/c4201e1aa0a75ce8f762293ac0550f13fe2eb220

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md](https://github.com/geeeyetee/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Preference_Variables.md)

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Preference_Variables.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md](https://github.com/geeeyetee/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Preference_Variables.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C4%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201712042107357228-1921%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=bqLgtnNC%2BO77g8pBxHtNllN273yVzaZ0Tku8Ec%2FKMY8%3D&st=2017-12-04T21%3A39%3A01Z&se=2018-01-04T21%3A44%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Those backslash characters are not extraneous. They are required by the tools we use to publish the About topic. Please see Issue #1806 and the updated [Style Guide](https://github.com/PowerShell/PowerShell-Docs/blob/staging/contributing/STYLE.md#about_-file-formatting).

**Comment by geeeyetee** [comment]
Many of them are visible on the rendered page; they should not be.

**Comment by geeeyetee** [comment]
@sdwheeler - Thank you for pointing out those resources earlier and for addressing this so promptly and thoroughly. When I search the rendered page following your commits https://github.com/PowerShell/PowerShell-Docs/pull/1924/commits/ab67cacafeaaa3b976fe8899bf1201c3e7137dc8 and https://github.com/PowerShell/PowerShell-Docs/pull/1924/commits/b0c3b79a9950ee8d234fed8d9a0fb42785f41980, I see that there are [now](https://github.com/PowerShell/PowerShell-Docs/blob/58371abe9db4b9a0e4e1eb82d39a9f9e187355f9/reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md) 0 instances of `\$` found versus 48 on [the previous live version](https://github.com/PowerShell/PowerShell-Docs/blob/b90e5e65c609b150b3bfc957f50465ab17fcfa8c/reference/6/Microsoft.PowerShell.Core/About/about_Preference_Variables.md).

**Pull request closed without merging**
