### PR TITLE
Fixing V6 module landing pages

### PR DESCRIPTION
**Pull request by TaraMeyer**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by TaraMeyer** [comment]
@joeyaiello - please review and merge this pr when validation completes.  It fixes the last remaining bug from the migration to docs.  Thanks!

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** File:6/CimCmdlets/CimCmdlets.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.LocalAccounts/Microsoft.PowerShell.LocalAccounts.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md not existed.
 - **[Error]** File:6/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md not existed.
 - **[Error]** File:6/Microsoft.WSMan.Management/Microsoft.WsMan.Management.md not existed.
 - **[Error]** File:6/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md not existed.
 - **[Error]** File:6/PSDiagnostics/PSDiagnostics.md not existed.
 - **[Error]** File:6/PSReadLine/PSReadline.md not existed.
 - **[Error]** File:6/PackageManagement/PackageManagement.md not existed.
 - **[Error]** File:6/Pester/Pester.md not existed.
 - **[Error]** File:6/PowerShellGet/PowerShellGet.md not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\d2ww-log-cc4c8e61\change-list-with-redirection.tsv.
 - **[Error]** File:../reference/6/CimCmdlets/CimCmdlets.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.LocalAccounts/Microsoft.PowerShell.LocalAccounts.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md not existed.
 - **[Error]** File:../reference/6/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md not existed.
 - **[Error]** File:../reference/6/Microsoft.WSMan.Management/Microsoft.WsMan.Management.md not existed.
 - **[Error]** File:../reference/6/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md not existed.
 - **[Error]** File:../reference/6/PSDiagnostics/PSDiagnostics.md not existed.
 - **[Error]** File:../reference/6/PSReadLine/PSReadline.md not existed.
 - **[Error]** File:../reference/6/PackageManagement/PackageManagement.md not existed.
 - **[Error]** File:../reference/6/Pester/Pester.md not existed.
 - **[Error]** File:../reference/6/PowerShellGet/PowerShellGet.md not existed.
 - **[Error]** Some error ocurred while parsing changelist file: W:\d2ww-log-cc4c8e61\change-list-with-redirection.tsv.
 - **[Warning]** &#39;W:\d2ww-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\d2ww-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C21%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708212009451591-1613%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TaraMeyer** [comment]
@joeyaiello - I've looked at the errors and it's very odd.  The report is saying that the module landing pages  do not exist, but I clearly see that they do.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/CimCmdlets/CimCmdlets.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/CimCmdlets/CimCmdlets.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Microsoft.PowerShell.Archive.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Microsoft.PowerShell.Core.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Diagnostics/Microsoft.PowerShell.Diagnostics.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Host/Microsoft.PowerShell.Host.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.LocalAccounts/Microsoft.PowerShell.LocalAccounts.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.LocalAccounts/Microsoft.PowerShell.LocalAccounts.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Management/Microsoft.PowerShell.Management.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Microsoft.PowerShell.Utility.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.WSMan.Management/Microsoft.WsMan.Management.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Microsoft.WSMan.Management/Microsoft.WsMan.Management.md) | :white_check_mark:Succeeded | |
[reference/6/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/PSDesiredStateConfiguration/PSDesiredStateConfiguration.md) | :white_check_mark:Succeeded | |
[reference/6/PSDiagnostics/PSDiagnostics.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/PSDiagnostics/PSDiagnostics.md) | :white_check_mark:Succeeded | |
[reference/6/PSReadLine/PSReadline.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/PSReadLine/PSReadline.md) | :white_check_mark:Succeeded | |
[reference/6/PackageManagement/PackageManagement.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/PackageManagement/PackageManagement.md) | :white_check_mark:Succeeded | |
[reference/6/Pester/Pester.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/Pester/Pester.md) | :white_check_mark:Succeeded | |
[reference/6/PowerShellGet/PowerShellGet.md](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/6/PowerShellGet/PowerShellGet.md) | :white_check_mark:Succeeded | |
[reference/docfx.json](https://github.com/TaraMeyer/PowerShell-Docs/blob/staging/reference/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708220241539187-1613%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by TaraMeyer** [comment]
@joeyaiello - are you able to merge this to live?  Thanks!

**Comment by TaraMeyer** [comment]
Hey @zjalexander , @joeyaiello , @juanpablojofre  - I can't verify this fix and close the bug until this pr is moved to staging. Can someone please merge to staging?

**Pull request merged**
