### PR TITLE
Fixing: Installing Windows PowerShell is outdated  

### LINKED ISSUE #1539: Outdated "Installing" and "Requirements" docs
Both of the following documents should cover at least PowerShell 5.1:

https://docs.microsoft.com/en-us/powershell/scripting/installing-windows-powershell?view=powershell-6
https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell-system-requirements?view=powershell-6

As we can now target documentation for the specific PowerShell versions (in the upper left-hand side corner), it would be even better if every selection would actually load a document that covers installation and requirements for that specific version (instead of just one page that covers all versions as we have now).

### PR DESCRIPTION
**Pull request by juanpablojofre**
This PR fixes #1539 and #1550

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/setup/Installing-Windows-PowerShell.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1550/reference/docs-conceptual/setup/Installing-Windows-PowerShell.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/topic/WinRMSecurity.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1550/reference/docs-conceptual/topic/WinRMSecurity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708151744132541-1578%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/setup/Installing-Windows-PowerShell.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1550/reference/docs-conceptual/setup/Installing-Windows-PowerShell.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/topic/WinRMSecurity.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1550/reference/docs-conceptual/topic/WinRMSecurity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708151751049098-1578%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/setup/Installing-Windows-PowerShell.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1550/reference/docs-conceptual/setup/Installing-Windows-PowerShell.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/topic/WinRMSecurity.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1550/reference/docs-conceptual/topic/WinRMSecurity.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C8%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201708151824394995-1578%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Eric ( @eslesar ), Sean (  @sdwheeler  ),
Could you please merge this PR?
Thanks,
-- JP

**Comment by alexandair** [comment]
Why is WinRMSecurity.md deleted as part of this PR?

**Comment by eslesar** [comment]
@juanpablojofre @sdwheeler Let's be sure we fix this before merging to live.

**Pull request merged**
