### PR TITLE
Updated 3.0,4.0,5.0,5.1,6.0 about_pipelines.md for #1262

### PR DESCRIPTION
**Pull request by kiazhi**
Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [x] This PR partially fixes the issue, and issue #1262 tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/6/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FAbout%2Fabout_pipelines.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FAbout%2Fabout_pipelines.md"></a>
### [reference/6/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706120526539018-1277%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/6/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FAbout%2Fabout_pipelines.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FAbout%2Fabout_pipelines.md"></a>
### [reference/6/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706120853040451-1277%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Comment_Based_Help.md)
[reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Comment_Based_Help.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Comment_Based_Help.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md)
[reference/6/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_Comment_Based_Help.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FAbout%2Fabout_Comment_Based_Help.md)
[reference/6/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_pipelines.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FAbout%2Fabout_pipelines.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Comment_Based_Help.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Comment_Based_Help.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Comment_Based_Help.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_pipelines.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FAbout%2Fabout_Comment_Based_Help.md"></a>
### [reference/6/About/about_Comment_Based_Help.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_Comment_Based_Help.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FAbout%2Fabout_pipelines.md"></a>
### [reference/6/About/about_pipelines.md](https://github.com/kiazhi/PowerShell-Docs/blob/staging/reference/6/About/about_pipelines.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706120901369237-1277%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@kiazhi ,
There are Git issues that prevent the rebasing and merge.
Please review and fix those issues to be able to merge the content.

**Comment by kiazhi** [comment]
Closed this Pull Request due to Git issues that prevent the rebasing and merge from a forked repository.

**Pull request closed without merging**
