### PR TITLE
Update Convert-String.md

### PR DESCRIPTION
**Pull request by jszabo98**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C27%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705271342191708-1236%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@jszabo98,
This PR has merge conflicts; would you please review and fix.
Best regards,
-- JP

**Comment by jszabo98** [comment]
I don't really know how to use Github.  But example 1 for the Convert-String doc plainly doesn't work:



PS> Convert-String -InputObject $Names -Example "Patti Fuller = Fuller, P."

Convert-String : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'InputObject'.
Specified method is not supported.
At line:1 char:29
+ Convert-String -InputObject $Names -Example "Patti Fuller = Fuller, P ...
+                             ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Convert-String], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.PowerShell.Commands.StringManipulation.ConvertStringComm
   and


Can you make it say this instead?  '-InputObject' usually doesn't take a list, and you can't have blanks around the '=' sign.

PS> $Names | Convert-String -Example "Patti Fuller=Fuller, P."


________________________________

**Comment by zjalexander** [comment]
Thanks for pointing out the issue, @jszabo98 . I opened an issue to track it and we'll resolve it when we have a minute.

**Pull request closed without merging**
