### PR TITLE
Removed duplicated lines

### PR DESCRIPTION
**Pull request by Meir017**
removed duplicated lines

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/module/how-to-write-a-powershell-binary-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/how-to-write-a-powershell-binary-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/how-to-write-a-powershell-binary-module?branch=pr-en-us-2649) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807051339060790-2649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7DzsE2V7BEJ2%2BfwY%2BeolM6%2FvCO%2F36cF5hkH338iUDZM%3D&st=2018-07-05T13%3A44%3A55Z&se=2018-08-05T13%3A49%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/module/how-to-write-a-powershell-binary-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/how-to-write-a-powershell-binary-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/how-to-write-a-powershell-binary-module?branch=pr-en-us-2649) |
[developer/module/writing-a-windows-powershell-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/writing-a-windows-powershell-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/writing-a-windows-powershell-module?branch=pr-en-us-2649) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807051343103364-2649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8hi%2FVFLhf28WLagspqtmglicJt%2BAHuaeoTahxC%2B6Cho%3D&st=2018-07-05T13%3A55%3A23Z&se=2018-08-05T14%3A00%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/module/how-to-write-a-powershell-binary-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/how-to-write-a-powershell-binary-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/how-to-write-a-powershell-binary-module?branch=pr-en-us-2649) |
[developer/module/installing-a-powershell-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/installing-a-powershell-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/installing-a-powershell-module?branch=pr-en-us-2649) |
[developer/module/modifying-the-psmodulepath-installation-path.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/modifying-the-psmodulepath-installation-path.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/modifying-the-psmodulepath-installation-path?branch=pr-en-us-2649) |
[developer/module/writing-a-windows-powershell-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/writing-a-windows-powershell-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/writing-a-windows-powershell-module?branch=pr-en-us-2649) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807051400258275-2649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ojDPhSL%2B11Yh6N8p01Ft1qX1n7fF4oOyQ6VWVmaTwd0%3D&st=2018-07-05T14%3A06%3A22Z&se=2018-08-05T14%3A11%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/module/how-to-write-a-powershell-binary-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/how-to-write-a-powershell-binary-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/how-to-write-a-powershell-binary-module?branch=pr-en-us-2649) |
[developer/module/importing-a-powershell-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/importing-a-powershell-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/importing-a-powershell-module?branch=pr-en-us-2649) |
[developer/module/installing-a-powershell-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/installing-a-powershell-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/installing-a-powershell-module?branch=pr-en-us-2649) |
[developer/module/modifying-the-psmodulepath-installation-path.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/modifying-the-psmodulepath-installation-path.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/modifying-the-psmodulepath-installation-path?branch=pr-en-us-2649) |
[developer/module/understanding-a-windows-powershell-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/understanding-a-windows-powershell-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/understanding-a-windows-powershell-module?branch=pr-en-us-2649) |
[developer/module/updatable-help-overview.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/updatable-help-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/updatable-help-overview?branch=pr-en-us-2649) |
[developer/module/writing-a-windows-powershell-module.md](https://github.com/Meir017/PowerShell-Docs/blob/patch-1/developer/module/writing-a-windows-powershell-module.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/module/writing-a-windows-powershell-module?branch=pr-en-us-2649) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C5%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807051401485349-2649%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7dmtNzOJhC7g1GB7PDryVfPSmiXEbh5iPk5fn9mXmfk%3D&st=2018-07-05T14%3A17%3A10Z&se=2018-08-05T14%3A22%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
@Meir017 Thanks for finding and fixing a bunch of these!  Your contribution is greatly appreciated!

**Pull request merged**
