### PR TITLE
Update Write-Progress.md

### PR DESCRIPTION
**Pull request by stahler**
Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by stahler** [comment]
minor fix with -PercentComplete parameter in the example 2

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md](https://github.com/stahler/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710161711138999-1768%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0J5sEbSEL9lDYzIV%2FI%2FsE4x1UvyMLjtOIOCT9GXzEds%3D&st=2017-10-16T17%3A40%3A10Z&se=2017-11-16T17%3A45%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Thanks Wes !! @stahler 

I opened #1769 to keep track of pending updates.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md](https://github.com/stahler/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Write-Progress.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710161714048557-1768%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sJ0xUg5bPVQxsVZdAGDkJ8stVkH2iluXKtLXlCH9nak%3D&st=2017-10-16T18%3A11%3A29Z&se=2017-11-16T18%3A16%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
