### PR TITLE
Update about_Foreach-Parallel.md

### PR DESCRIPTION
**Pull request by markroloff**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [x] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md)
[reference/4.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/4.0/PSWorkflow/About/about_Foreach-Parallel.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md)
[reference/5.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/5.0/PSWorkflow/About/about_Foreach-Parallel.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md)

<a name="reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md"></a>
### [reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md"></a>
### [reference/4.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/4.0/PSWorkflow/About/about_Foreach-Parallel.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md"></a>
### [reference/5.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/5.0/PSWorkflow/About/about_Foreach-Parallel.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C6%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710060300190678-1729%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=qoP%2FuVYrLDDHdr7CLJJ6OzyaOoV3QHBfHkeMiqypwXE%3D&st=2017-10-06T03%3A25%3A40Z&se=2017-10-07T03%3A35%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FGet-Date.md)
[reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Management%2FGet-ChildItem.md)
[]() | :x:Error | | [Details](#user-content-)
[reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FGet-Date.md"></a>
### [reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md)
 - **[Error]** Error transforming model &quot;W:\3tku-o-16a24623\raw-\wqoj5ldj.ubp\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Utility\Get-Date.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Utility/Get-Date.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Management%2FGet-ChildItem.md"></a>
### [reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md)
 - **[Error]** Error transforming model &quot;W:\3tku-o-16a24623\raw-\wqoj5ldj.ubp\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Management\Get-ChildItem.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Management/Get-ChildItem.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\3tku-o-16a24623\raw-\wqoj5ldj.ubp\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Utility\Get-Date.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Utility/Get-Date.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 
 - **[Warning]** &#39;W:\3tku-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\3tku-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

<a name="reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md"></a>
### [reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C11%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710111717384195-1729%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FemfF0xyCTLjqPLD7%2FcFGItbtpHmbw9%2FHaNzgQWvEcM%3D&st=2017-10-11T17%3A21%3A01Z&se=2017-11-11T17%3A26%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Management%2FGet-ChildItem.md)
[reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FGet-Date.md)
[]() | :x:Error | | [Details](#user-content-)
[reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Management%2FGet-ChildItem.md"></a>
### [reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md)
 - **[Error]** Error transforming model &quot;W:\i35l-o-16d352da\raw-\s1loo23h.ywa\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Management\Get-ChildItem.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Management/Get-ChildItem.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FGet-Date.md"></a>
### [reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md)
 - **[Error]** Error transforming model &quot;W:\i35l-o-16d352da\raw-\s1loo23h.ywa\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Utility\Get-Date.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Utility/Get-Date.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\i35l-o-16d352da\raw-\s1loo23h.ywa\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Management\Get-ChildItem.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Management/Get-ChildItem.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 
 - **[Warning]** &#39;W:\i35l-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\i35l-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

<a name="reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md"></a>
### [reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C11%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710111852087449-1729%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Vmwld1CV2dJLCkKujskCKPBr0dKmWwNYeZpo9769KpM%3D&st=2017-10-11T18%3A55%3A26Z&se=2017-11-11T19%3A00%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Close and repoen to see if this allows to merge

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Management%2FGet-ChildItem.md)
[reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FGet-Date.md)
[]() | :x:Error | | [Details](#user-content-)
[reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Management%2FGet-ChildItem.md"></a>
### [reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Management/Get-ChildItem.md)
 - **[Error]** Error transforming model &quot;W:\z04a-o-ddbec510\raw-\t2vi50am.4gx\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Management\Get-ChildItem.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Management/Get-ChildItem.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FGet-Date.md"></a>
### [reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Get-Date.md)
 - **[Error]** Error transforming model &quot;W:\z04a-o-ddbec510\raw-\t2vi50am.4gx\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Utility\Get-Date.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Utility/Get-Date.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 

<a name=""></a>
### []()
 - **[Error]** Error transforming model &quot;W:\z04a-o-ddbec510\raw-\t2vi50am.4gx\rawmodel\powershell-3.0\module\Microsoft.PowerShell.Management\Get-ChildItem.raw.json&quot; generated from &quot;3.0/Microsoft.PowerShell.Management/Get-ChildItem.md&quot; using &quot;AzureCli.html.primary.js&quot;. Error running GetOptions function inside template preprocessor: 
 - **[Warning]** &#39;W:\z04a-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\z04a-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.

<a name="reference%2F3.0%2FPSWorkflow%2FAbout%2Fabout_Foreach-Parallel.md"></a>
### [reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md](https://github.com/markroloff/PowerShell-Docs/blob/staging/reference/3.0/PSWorkflow/About/about_Foreach-Parallel.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710121538548490-1729%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Dan1jvyUpHhbyW5CcURABR%2BIqCH7RkmBN5JYw8BTRj8%3D&st=2017-10-12T15%3A41%3A48Z&se=2017-11-12T15%3A46%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
