### PR TITLE
updates for formatting commands

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[contributing/3-STYLE-GUIDE.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-styleguide/contributing/3-STYLE-GUIDE.md) | :white_check_mark:Succeeded | |
[contributing/4-MARKDOWN-SPECIFICS.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-styleguide/contributing/4-MARKDOWN-SPECIFICS.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C29%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808292042376679-2870%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=52d13mHYEB7EZbIveU7939BODbPliSmoL2rCSsv4XXs%3D&st=2018-08-29T20%3A52%3A55Z&se=2018-09-29T20%3A57%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Prematurely removed the branch.

**Comment by sdwheeler** [comment]
#sign-off

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[contributing/3-STYLE-GUIDE.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-styleguide/contributing/3-STYLE-GUIDE.md) | :white_check_mark:Succeeded | |
[contributing/4-MARKDOWN-SPECIFICS.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-styleguide/contributing/4-MARKDOWN-SPECIFICS.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C29%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808292109268727-2870%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5%2BiDQqH8lqtfp%2BuFGtQpEbH2P03pzJESHj%2FwWM4Eggk%3D&st=2018-08-29T21%3A20%3A59Z&se=2018-09-29T21%3A25%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
