### PR TITLE
Updated Get-Help Markdown

### PR DESCRIPTION
**Pull request by MSAdministrator**
Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

This is related to a larger body of work.  This was initiated by and is related to #1511 & #1025

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/Get-Help.md](https://github.com/MSAdministrator/PowerShell-Docs/blob/msadministrator_get_help_markdown/reference/3.0/Microsoft.PowerShell.Core/Get-Help.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FGet-Help.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FGet-Help.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/Get-Help.md](https://github.com/MSAdministrator/PowerShell-Docs/blob/msadministrator_get_help_markdown/reference/3.0/Microsoft.PowerShell.Core/Get-Help.md)
 - **[Error]** Unable to load file: 3.0/Microsoft.PowerShell.Core/Get-Help.md via processor: AzureCliDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** Markdown.MAML.Transformer.HelpSchemaException: :165:(1597) &#39;```powershell
PS C:\&gt; Update-Help
```

&#39;
 Expect Heading
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801180511049703-2070%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=A4q6vOIiRRUMeZpVqONLDQ%2FCoA2pty1qfjusFyiaszI%3D&st=2018-01-18T05%3A10%3A53Z&se=2018-02-18T05%3A15%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by MSAdministrator** [comment]
I can look at this later, but I’m not seeing exactly why this failed.

**Comment by sdwheeler** [comment]
@MSAdministrator can you PM me in Slack@swsamwa?

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/Get-Help.md](https://github.com/MSAdministrator/PowerShell-Docs/blob/msadministrator_get_help_markdown/reference/3.0/Microsoft.PowerShell.Core/Get-Help.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FGet-Help.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FGet-Help.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/Get-Help.md](https://github.com/MSAdministrator/PowerShell-Docs/blob/msadministrator_get_help_markdown/reference/3.0/Microsoft.PowerShell.Core/Get-Help.md)
 - **[Error]** Unable to load file: 3.0/Microsoft.PowerShell.Core/Get-Help.md via processor: AzureCliDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** Markdown.MAML.Transformer.HelpSchemaException: :167:(1746) &#39;```powershell
PS C:\&gt; Update-Help
```

&#39;
 Expect Heading
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801182044227745-2070%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PeNOcEtFgXyF2DBtskEgcCB24tXsRtcpETGnfCLBjJQ%3D&st=2018-01-18T20%3A45%3A13Z&se=2018-02-18T20%3A50%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@MSAdministrator - is this a dupe of #2074? Should we close this?

**Comment by sdwheeler** [comment]
Closing as duplicate

**Pull request closed without merging**
