### PR TITLE
closes #3034 - document new v6 features of Measure-Object

### LINKED ISSUE #3034: Docs needed for 'Fix for #6855 - Measure-Object should handle scriptblock properties.'
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/6934

### PR DESCRIPTION
**Pull request by bobbytreed**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[4c56349](https://github.com/bobbytreed/PowerShell-Docs/pull/3565/commits/4c5634913e781af70391ddb81b215062426a60ce)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 11 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[4c56349](https://github.com/bobbytreed/PowerShell-Docs/pull/3565/commits/4c5634913e781af70391ddb81b215062426a60ce)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 18 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[4c56349](https://github.com/bobbytreed/PowerShell-Docs/pull/3565/commits/4c5634913e781af70391ddb81b215062426a60ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Measure-Object.md](https://github.com/bobbytreed/PowerShell-Docs/blob/bobbyreed-issue3034/reference/6/Microsoft.PowerShell.Utility/Measure-Object.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/measure-object?view=powershell-6&branch=pr-en-us-3565) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901171532397969-3565%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TaWlb9%2Bnhg0QZOH2VOiebJTffEWCMt7wLVIWbXaYMLk%3D&st=2019-01-17T15%3A41%3A13Z&se=2019-02-17T15%3A46%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by bobbytreed** [comment]
#sign-off

**Pull request merged**
