### PR TITLE
ComputerName parameter not fully spelled out

### PR DESCRIPTION
**Pull request by gengle**
Version(s) of document impacted
------------------------------
- [X] Impacts 6.1 document
- [X] Impacts 6.0 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [X] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [X] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by gengle** [comment]
I am not sure what versions this typo impacts.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/gengle/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201806151627140377-2586%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JrAtsEu1X%2BCmLyRfJryflNgNFJa9fwT7usR1bA37e0M%3D&st=2018-06-15T16%3A32%3A04Z&se=2018-07-16T16%3A37%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
@gengle Thanks for noticing this!  Since the same issue exists in 3/4/5.0/5.1 docs, in addition to 6 that you fixed, can you please fix them all at the same time?  We like to keep such fixes in sync when it exists in multiple versions of the same content.  Thanks!

**Comment by gengle** [comment]
@DCtheGeek sure thing. I'll make sure all versions are updated.

**Comment by gengle** [comment]
@DCtheGeek think I updated them all.  4.0 looked fine to me.

**Comment by DCtheGeek** [comment]
@gengle Great, thanks!  I see you are correct about the 4.0 doc.  Once all the validations/builds complete, I think this is good to go.  Thank you again!

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/gengle/PowerShell-Docs/blob/patch-1/reference/3.0/Microsoft.PowerShell.Core/Enter-PSSession.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/gengle/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Core/Enter-PSSession.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/gengle/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/Enter-PSSession.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/gengle/PowerShell-Docs/blob/patch-1/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C6%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201806151752044417-2586%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kwOs0xu5V4GrPYSm4wfp%2Fdn7743QjJ6oMF8GK8FdnXU%3D&st=2018-06-15T17%3A56%3A46Z&se=2018-07-16T18%3A01%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
