### PR TITLE
CC55771: Fix links

### PR DESCRIPTION
**Pull request by carolinacmoravia**
Hello, @sethvs,

This proposed file change comes from this Community Contribution:  https://github.com/PowerShell/powerShell-Docs.ru-ru/pull/13/files

Please, help to check this proposed file change into the article and help to merge if you agree with fix. If not, please, let me know either if you would like me to fix it in another way within this PR, if you prefer to fix it in another PR or if I should close this PR as by-design. In case of using another PR, please, let me know of your PR number, so we can confirm and close this PR.

Many thanks in advance.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md](https://github.com/carolinacmoravia/PowerShell-Docs/blob/patch-6/reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804251921314520-2360%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=26A1f5lqLvzsTWExEbkviC%2Ffll95JhJelpCc1a86FWE%3D&st=2018-04-25T19%3A26%3A52Z&se=2018-05-26T19%3A31%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md](https://github.com/carolinacmoravia/PowerShell-Docs/blob/patch-6/reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804251941343400-2360%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=f781%2Beb%2BXS9hk0X4l%2Bcmm7bLh5IO8CQq9YBftysWods%3D&st=2018-04-25T19%3A47%3A39Z&se=2018-05-26T19%3A52%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md](https://github.com/carolinacmoravia/PowerShell-Docs/blob/patch-6/reference/docs-conceptual/core-powershell/SSH-Remoting-in-PowerShell-Core.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C26%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804261411499746-2360%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vHyLGX7CXdgNDsneNNUQZnTdXTTJRAajj%2BCmHJhlsfU%3D&st=2018-04-26T14%3A34%3A25Z&se=2018-05-27T14%3A39%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sethvs** [comment]
Hello.
I'm OK with the result in this repo but would like to add the fixes to the powerShell-Docs.ru-ru repo too.

**Pull request merged**
