### PR TITLE
Please fix incomplete sentence

### PR DESCRIPTION
**Pull request by v-jacard**
Hi @eslesar,
Localization team found an incomplete sentence "Note: The user running the".
I've placed a comment in article to indicate the location.
Please help to reply what the full sentence should be in this PR or let me know if you will fix in another PR.
Thank you,
Jason

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701161922354792-954%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C19%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701191755082115-954%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eslesar** [comment]
I completed the sentence.

**Comment by eslesar** [comment]
@HemantMahawar @juanpablojofre can you review and merge this PR?

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C19%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701191805165199-954%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@eslesar  Should the link to publish-dscconfiguration cmdlet be to [msdn 5.1 reference](https://msdn.microsoft.com/en-us/powershell/reference/5.1/psdesiredstateconfiguration/publish-dscconfiguration)?

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C19%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701191838433321-954%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by eslesar** [comment]
@HemantMahawar Yes, thanks. Updated.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C19%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701191839457187-954%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
