### PR TITLE
Added a remark paragraph according to issue #8607

### PR DESCRIPTION
**Pull request by fullenw1**
This is a proposition of remark. But I don't know if referring to a Github issue and/or mentioning a possible future change is compliant with the current DOCS rules. Please update if necessary, or I can do it if you say me what to change...

Version(s) of document impacted
------------------------------
- [X] Impacts 6.next document
- [X] Impacts 6 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[bb62b98](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/bb62b985422f891ec5d290fcfea025d0ec4111fc)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[bb62b98](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/bb62b985422f891ec5d290fcfea025d0ec4111fc)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 19 sec(s)_

**Comment by sdwheeler** [comment]
Pending shiproom discussion.

**Comment by sdwheeler** [comment]
Approved in shiproom

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[9fe983b](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/9fe983b066d74e1ab7ce93dd770645a3bd9a074d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[9fe983b](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/9fe983b066d74e1ab7ce93dd770645a3bd9a074d)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 16 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[9fe983b](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/9fe983b066d74e1ab7ce93dd770645a3bd9a074d)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Management/Test-Path.md](https://github.com/fullenw1/PowerShell-Docs/blob/patch-5/reference/6/Microsoft.PowerShell.Management/Test-Path.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Management%2FTest-Path.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Management%2FTest-Path.md"></a>
### [reference/6/Microsoft.PowerShell.Management/Test-Path.md](https://github.com/fullenw1/PowerShell-Docs/blob/patch-5/reference/6/Microsoft.PowerShell.Management/Test-Path.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Management/Test-Path.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :344:(924) &#39;&gt; [!CAUTION] 
&gt; 
&gt; Up to PowerShell version 6.1....&#39;
 Expect Heading

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901232204322257-3537%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pfeu0wtsPrRLlxAX9ZBxibCO48aZ7ktAZ8CEDytD5LA%3D&st=2019-01-23T22%3A13%3A38Z&se=2019-02-23T22%3A18%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3b9a851](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/3b9a851be0aba572336c29e8f8bd649a2cdb932e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3b9a851](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/3b9a851be0aba572336c29e8f8bd649a2cdb932e)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 16 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3b9a851](https://github.com/fullenw1/PowerShell-Docs/pull/3537/commits/3b9a851be0aba572336c29e8f8bd649a2cdb932e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Management/Test-Path.md](https://github.com/fullenw1/PowerShell-Docs/blob/patch-5/reference/6/Microsoft.PowerShell.Management/Test-Path.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/test-path?view=powershell-6&branch=pr-en-us-3537) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901232241482694-3537%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vkmVUef%2FL%2F3YhH9cySs60KLmRZ107e9ZpJ59GvjKQSA%3D&st=2019-01-23T22%3A50%3A03Z&se=2019-02-23T22%3A55%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by fullenw1** [comment]
Thanks for the merge. However there is a typo error.
Currently, the text says:

> the Test-Path cmdlet simply the PathType switch

But it should be:

"the Test-Path cmdlet simply **ignores** the PathType switch"

**Comment by sdwheeler** [comment]
Thanks, this has been fixed in #3598

**Pull request merged**
