### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by VertigoRay**
Version(s) of document impacted
------------------------------
- [X] Impacts 6.1 document
- [X] Impacts 6.0 document
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_script_internationalization?view=powershell-6&branch=pr-en-us-2743) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C28%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201807281818293542-2743%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=B1tbyq71nZJ8Jp58r6YhaaHJ2a9FQO0tGOeiy3yOawc%3D&st=2018-07-28T18%3A28%3A18Z&se=2018-08-28T18%3A33%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
@VertigoRay Thanks for spotting this!  Can you also please update the same file / fix in the 3/4/5.0/5.1 versions of the file in this PR so they will all be corrected and consistent?  Thanks again!

**Comment by VertigoRay** [comment]
@DCtheGeek Done. 😏

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_script_internationalization?view=powershell-3.0&branch=pr-en-us-2743) (powershell-3.0) | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md)
[reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_script_internationalization?view=powershell-4.0&branch=pr-en-us-2743) (powershell-4.0) | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md)
[reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_script_internationalization?view=powershell-5.0&branch=pr-en-us-2743) (powershell-5.0) | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md)
[reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_script_internationalization?view=powershell-5.1&branch=pr-en-us-2743) (powershell-5.1) | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md)
[reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_script_internationalization?view=powershell-6&branch=pr-en-us-2743) (powershell-6) | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/3.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/4.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/5.0/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/5.1/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Script_Internationalization.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md](https://github.com/VertigoRay/PowerShell-Docs/blob/patch-3/reference/6/Microsoft.PowerShell.Core/About/about_Script_Internationalization.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C1%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201808010411427859-2743%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rkcHw0atQgyvdW0IgA43%2BOY%2FkDsNbCoEVZTfxW8LuQE%3D&st=2018-08-01T04%3A22%3A29Z&se=2018-09-01T04%3A27%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by DCtheGeek** [comment]
@VertigoRay Thanks for doing the rest of the files and contributing this fix, it is much appreciated!

**Comment by VertigoRay** [comment]
@DCtheGeek  Absolutely!  I love that you allow edits now so things can be mantained by the community that loves the products. I think this will allow better growth of the *real* documentation and less spin-off sites to supplement where the *real* documentation is lacking.

**Pull request merged**
