### PR TITLE
Changed Synopsis for Add-Type in Version 5.1

### PR DESCRIPTION
**Pull request by sauravMSFT**
Made a change in Synopsis for Add-Type in version 5.1 docs.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701221754444533-982%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701231631356261-982%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@sauravMSFT Thanks for your contribution.

**Pull request merged**
