### PR TITLE
Update Import-LocalizedData.md

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Customer hit an issue where the data file was saved as ANSI so the resulting content wasn't rendered correctly

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md](https://github.com/PowerShell/PowerShell-Docs/blob/SteveL-MSFT-patch-1/reference/5.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C24%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201703242215211084-1112%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
@SteveL-MSFT can you add the template back in to your PR and mention what versions are affected and if this applies to other versions than 5.1?

**Comment by SteveL-MSFT** [comment]
@zjalexander I don't know if exactly which versions of PS are affected, but I suspect all that support this cmdlet.  I don't recall seeing a template as I believe I submitted this via MSDN.

**Comment by juanpablojofre** [comment]
@zjalexander,
We need to fix the way users can contribute when coming from direct links, i.e. from MSDN.
They see no template, neither have any warning on how to contribute.

**Comment by zjalexander** [comment]
I just clicked the "contribute" button on MSDN, edited a file, and created a PR from the edit. Here's what I see. Please let me know if you see something different. 
image

**Comment by SteveL-MSFT** [comment]
test


Version(s) of document impacted
------------------------------
- [X] Impacts 5.1 document
- [X] Impacts 5.0 document
- [X] Impacts 4.0 document
- [X] Impacts 3.0 document


Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

**Comment by SteveL-MSFT** [comment]
Anything else needed to merge?

**Comment by zjalexander** [comment]
>This PR partially fixes the issue, and issue # tracks the remaining work

You need to either check this box and create an issue to track the remaining work, or update the other docs.

**Comment by SteveL-MSFT** [comment]
Updated the other docs

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md](https://github.com/PowerShell/PowerShell-Docs/blob/SteveL-MSFT-patch-1/reference/3.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md](https://github.com/PowerShell/PowerShell-Docs/blob/SteveL-MSFT-patch-1/reference/4.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md](https://github.com/PowerShell/PowerShell-Docs/blob/SteveL-MSFT-patch-1/reference/5.0/Microsoft.PowerShell.Utility/Import-LocalizedData.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md](https://github.com/PowerShell/PowerShell-Docs/blob/SteveL-MSFT-patch-1/reference/5.1/Microsoft.PowerShell.Utility/Import-LocalizedData.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C24%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704241805267567-1112%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
AppVeyor actually passed, status isn't getting reported back correctly for whatever reason:
```
Tests completed in 2.72s
Tests Passed: 7, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 
Collecting artifacts...
Found artifact 'updatablehelp' matching 'updatablehelp' path
Uploading artifacts...
[1/1] updatablehelp.zip (7,960,345 bytes)...100%
Build success
```

**Pull request merged**
