### PR TITLE
Update Get-Item.md

### PR DESCRIPTION
**Pull request by skycommand**
Proof-read some of the examples. The first two were wrong: The user must be in the ps-test folder for the result shown to happen. The subsequent examples didn't have their results shown. I added them.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Management/Get-Item.md](https://github.com/skycommand/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Management/Get-Item.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C11%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201712111023528996-1942%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AaRNLxmdGL958FLQ2F3Hs%2BcDaLiSlqc3A1km7ORENFg%3D&st=2017-12-11T10%3A48%3A02Z&se=2018-01-11T10%3A53%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by skycommand** [comment]
I seriously did not see this coming: The file name in the Saldana conversation reads "reference/5.1/Microsoft.PowerShell.Management/Get-Item.md". This means I must have filled in the templates that were meant for files in "/reference" folder but I deleted.

I deleted them because I thought the file path was "module/Microsoft.PowerShell.Management/Get-Item". Argh!

**Comment by sdwheeler** [comment]
@skycommand - this normal. The URL path to the published article is  "module/Microsoft.PowerShell.Management/Get-Item". The GitHub path is "reference/5.1/Microsoft.PowerShell.Management/Get-Item.md"

**Comment by skycommand** [comment]
Thanks. So, I have a question: When will I see the changes going live?

**Comment by sdwheeler** [comment]
@skycommand I try to do a merge to Live at least once a week.

**Pull request merged**
