### PR TITLE
Add /norestart in the command for installing

### PR DESCRIPTION
**Pull request by peterneave**
Make users (like me) aware that the /quiet command will reboot the machine without intervention

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/install-configure.md](https://github.com/peterneave/PowerShell-Docs/blob/patch-1/wmf/5.1/install-configure.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801170545534115-2065%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yFMuiWBK7M0BC%2FYt1aBXy%2FpZI1puHjhogRbGgxnPMcM%3D&st=2018-01-17T06%3A10%3A05Z&se=2018-02-17T06%3A15%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by exchange12rocks** [comment]
For consistency, I suggest you to add those parameters into [wmf/5.0/install.md](../blob/staging/wmf/5.0/install.md) as well. You could do this just by implementing changes in the "peterneave:patch-1" branch - they will be automatically added to this pull-request.

**Comment by peterneave** [comment]
As requested @exchange12rocks

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.0/install.md](https://github.com/peterneave/PowerShell-Docs/blob/patch-1/wmf/5.0/install.md) | :white_check_mark:Succeeded | |
[wmf/5.1/install-configure.md](https://github.com/peterneave/PowerShell-Docs/blob/patch-1/wmf/5.1/install-configure.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801171124584737-2065%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8wXF1BekOnLMiB0Pdu%2ByYCwz1qjSQhgInT9KjkTeNKM%3D&st=2018-01-17T11%3A47%3A04Z&se=2018-02-17T11%3A52%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@zjalexander @joeyaiello - What do you think about this change? Do we need to add a reboot step?

**Comment by sdwheeler** [comment]
@peterneave Thanks for your contribution. I feel your pain about the reboot. But it is necessary. I talked this over with Zach. We will update the article to talk about the reboot. But I won't take this PR as is. I will have an alternate update to this article by tomorrow.

**Pull request closed without merging**
