### PR TITLE
Update Get-ChildItem.md

### PR DESCRIPTION
**Pull request by doctordns**
This pull request refines the Get-Child Item cmdlet's Help information.

1. Added a description to the Attributes parameter.
2. In notes section at the end of the article, added details of retrieving Hidden items by using the -Attributes parameter and specifying Hidden.
3. In -Exclude, noted that Wild cards are accepted. 
4. In -Include, noted that Wild cards are accepted. 
5. In -Path, noted that wildcards are accepted.
6. In -Include, minor grammatical change
7. -Path parameter redrafted description.
8. Added a description to the depth parameter.
9. Clarify the -Filter parameter's  last sentence.
10. mentioned the -Recurse parameter in the cmdlet's description.
11. Added parameter descriptions for the Directory, File, Hidden, ReadOnly, and System parameters.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C26%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612261133150296-924%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by doctordns** [comment]
this is a set of edits that tidy up one Cmdlet. I hope to get to look at more over the coming weeks!

**Comment by doctordns** [comment]
How long, after going to staging, does a pull request actually hit the live documentation - both that on MSDN and downloaded help text.

**Comment by zjalexander** [comment]
@doctordns webpage takes a few hours after someone does a merge to live from staging.
downloaded documentation isn't hooked up yet.

also, this is one of the changes that needs to be ported between the different versions. I can see many of the same issues in 4.0 for instance.

**Comment by doctordns** [comment]
zjalexander: thanks. I'm just not familiar with the workflow after the point my PR is accepted. And I'm curious! :-) Is there any documentation that describes how this all works? I'm most interested in what happens after staging branch gets merged back into the main. I know we can see it on here, but how does it get to the MSDN site, and how does it get to the downloadable site so I can get it from Get-Help locally. 

For this PR, I see the 5.1 content is now up on MSDN. Cool. So as soon as I get a moment, I can fix the older content. I notice a few areas in the 5.1 content that can further improved. The plan is to update the last 3 versions (4, 5, and 5.1) and issue relevant pull requests.

**Comment by zjalexander** [comment]
@doctordns no, we don't have full documentation of the workflow at the moment. that's one of the things i'm working with @eslesar and @juanpablojofre on. 

eventually we are going to use PlatyPS to have our github help go back into downloadable help (aka get-help) , that's something @joeyaiello is working on.

**Pull request merged**
