### PR TITLE
Updated Measure-Command.md for 4.0 #1233 #1259

### PR DESCRIPTION
**Pull request by kiazhi**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [x] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [x] This PR partially fixes the issue, and issue #1259 tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/kiazhi/PowerShell-Docs/blob/patch-4/reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md)

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md"></a>
### [reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/kiazhi/PowerShell-Docs/blob/patch-4/reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706121033518394-1281%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/kiazhi/PowerShell-Docs/blob/patch-4/reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md)

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md"></a>
### [reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/kiazhi/PowerShell-Docs/blob/patch-4/reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706121049571192-1281%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@kiazhi,

Your changes are breaking the build process.
It has to do with the way [PlatyPS](https://github.com/PowerShell/platyPS/blob/master/platyPS.schema.md) reads the cmdlet reference documentation. PlatyPS can be very picky when it comes to casing and header level.
Please, review and update your edits, so they can make it through the build process.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/kiazhi/PowerShell-Docs/blob/patch-4/reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md)

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FMeasure-Command.md"></a>
### [reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md](https://github.com/kiazhi/PowerShell-Docs/blob/patch-4/reference/4.0/Microsoft.PowerShell.Utility/Measure-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706122356223709-1281%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
