### PR TITLE
Add remoting requirements

### PR DESCRIPTION
**Pull request by zjalexander**
add remoting requirements as first step for troubleshooting

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702092052356549-1028%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@zjalexander DSC requires WinRM to be enabled not PS Remoting. See under **WinRM Dependency** section in https://msdn.microsoft.com/en-us/powershell/wmf/5.1/install-configure for the details.

**Comment by zjalexander** [comment]
thanks!! take another look @HemantMahawar ?

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702092349185126-1028%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C10%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702100608470280-1028%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
