### PR TITLE
Update searching-by-compatibility.md

### PR DESCRIPTION
**Pull request by doctordns**
Added details of searching using PowerShell
Fixed an over long heading

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[925009d](https://github.com/doctordns/PowerShell-Docs/pull/3459/commits/925009d2cdd4f7f8f47e9877ccd4c160a8268b1c)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 25 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[925009d](https://github.com/doctordns/PowerShell-Docs/pull/3459/commits/925009d2cdd4f7f8f47e9877ccd4c160a8268b1c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/how-to/finding-packages/searching-by-compatibility.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-9/gallery/how-to/finding-packages/searching-by-compatibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/gallery/how-to/finding-packages/searching-by-compatibility?branch=pr-en-us-3459) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201812202228585949-3459%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AzCpVF%2FCt9rDh0jAwoZeyOxVGGVI5HFhaQVJWJQsyUI%3D&st=2018-12-20T22%3A37%3A49Z&se=2019-01-20T22%3A42%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[e1f1edc](https://github.com/doctordns/PowerShell-Docs/pull/3459/commits/e1f1edcf193cf434816da5ddde4d19f249553b58)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[e1f1edc](https://github.com/doctordns/PowerShell-Docs/pull/3459/commits/e1f1edcf193cf434816da5ddde4d19f249553b58)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 24 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[e1f1edc](https://github.com/doctordns/PowerShell-Docs/pull/3459/commits/e1f1edcf193cf434816da5ddde4d19f249553b58)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/how-to/finding-packages/searching-by-compatibility.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-9/gallery/how-to/finding-packages/searching-by-compatibility.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/gallery/how-to/finding-packages/searching-by-compatibility?branch=pr-en-us-3459) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201812202250312267-3459%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CU6cy5JT2xp5fV7f8HUilcO%2FRMxIGi%2FJF%2BnNUo5l4v0%3D&st=2018-12-20T22%3A59%3A45Z&se=2019-01-20T23%3A04%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by doctordns** [comment]
Thanks kfor the catches !

**Pull request merged**
