### PR TITLE
update remote cmdlets for new hostname syntax

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Update documentation to reflect changes in PR https://github.com/PowerShell/PowerShell/pull/6558

Note that VSCode removed some trailing whitespace and not sure if critical to retain

Version(s) of document impacted
------------------------------
- [X] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [X] The documented feature was introduced in version (6.1) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/PowerShell/PowerShell-Docs, working directory: W:\wia0-s, target branch: staging, target branch commit: 2ba51e581d1367803d1062add25a47624ad9f497, source branch: 0ae6c9a919c86374850ceaa6cd17832e/ssh-hostname2, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804041234359339-2298%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=NCn1sn43a2jOCiMHHnuDuaW6J3Qoj6W7VExmHIxQuF4%3D&st=2018-04-04T12%3A30%3A11Z&se=2018-05-05T12%3A35%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/SteveL-MSFT/PowerShell-Docs/blob/ssh-hostname2/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/SteveL-MSFT/PowerShell-Docs/blob/ssh-hostname2/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804041236121110-2298%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=BXUrEuN5yeRhHA7mCLNEI%2FvOrUD5Ku1dCI5e3Ba7Lwk%3D&st=2018-04-04T12%3A40%3A05Z&se=2018-05-05T12%3A45%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/SteveL-MSFT/PowerShell-Docs/blob/ssh-hostname2/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/SteveL-MSFT/PowerShell-Docs/blob/ssh-hostname2/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/SteveL-MSFT/PowerShell-Docs/blob/ssh-hostname2/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C4%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804042349342146-2298%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TL46vS6l%2FKpprEIxVRfA0wllEtnztBfwQBrR8NH0zug%3D&st=2018-04-04T23%3A53%3A38Z&se=2018-05-05T23%3A58%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by SteveL-MSFT** [comment]
@sdwheeler the code PR was merged so we should merge this

**Pull request closed without merging**
