### PR TITLE
C48807: Wrong table content's position

### PR DESCRIPTION
**Pull request by carolinacmoravia**
@eslesar, 
There is an incorrect table structure causing content placed in the wrong position. Could you, please, help to merge this PR?
Many thanks in advance.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/metaConfig.md](https://github.com/carolinacmoravia/PowerShell-Docs/blob/patch-1/dsc/metaConfig.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706151820114600-1325%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
closed and reopened to force rebuild

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/metaConfig.md](https://github.com/carolinacmoravia/PowerShell-Docs/blob/patch-1/dsc/metaConfig.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C16%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706161724114071-1325%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/metaConfig.md](https://github.com/carolinacmoravia/PowerShell-Docs/blob/patch-1/dsc/metaConfig.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C26%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706261813094142-1325%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
