### PR TITLE
updated docs for `-FollowRelLink` and `-MaximumFollowRelLink` switches

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Version(s) of document impacted
------------------------------
- [X] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [X] The documented feature was introduced in version 6 of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C24%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705242246304916-1232%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705251531251114-1232%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by SteveL-MSFT** [comment]
@saldana @juanpablojofre can you help with understanding the issue with OpenPublishing Build?  There's no error to look at.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C5%5C30%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201705302328234378-1232%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/SteveL-MSFT/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C1%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706010701162930-1232%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md](https://github.com/SteveL-MSFT/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-RestMethod.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706020315208356-1232%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
