### PR TITLE
Merging latest updates to live

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 16**: **[Error]** Restore nuget package W:\uwet-s\.optemp\packages\opbuild.scripts.1.47.2\tools\packages.config in folder:W:\uwet-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error:  Errors in packages.config projects     Unable to find version &#39;1.47.2&#39; of package &#39;opbuild.initializecrrtool&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://nuget.org/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://nuget.org/api/v2/&#39;.       https://www.myget.org/F/op/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/op/api/v2/&#39;.       https://www.myget.org/F/op-dev/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2/&#39;.       https://www.myget.org/F/docfx-dev/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/docfx-dev/api/v2/&#39;.       https://www.myget.org/F/docfx/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/docfx/api/v2/&#39;.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804091613109944-2319%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vCPEtBQnFUYx4lIOOLdAIgPO17qIcTM1v9CFNlB3L7o%3D&st=2018-04-09T16%3A08%3A59Z&se=2018-05-10T16%3A13%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 16**: **[Error]** Restore nuget package W:\fv31-s\.optemp\packages\opbuild.scripts.1.47.2\tools\packages.config in folder:W:\fv31-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error:  Errors in packages.config projects     Unable to find version &#39;1.47.2&#39; of package &#39;opbuild.initializecrrtool&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://nuget.org/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://nuget.org/api/v2/&#39;.       https://www.myget.org/F/op/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/op/api/v2/&#39;.       https://www.myget.org/F/op-dev/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2/&#39;.       https://www.myget.org/F/docfx-dev/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/docfx-dev/api/v2/&#39;.       https://www.myget.org/F/docfx/api/v2/: Package &#39;opbuild.initializecrrtool.1.47.2&#39; is not found on source &#39;https://www.myget.org/F/docfx/api/v2/&#39;.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804091634426498-2319%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=64%2Bh3JmTBv7w2hHhyO3CLXSlOnU9yt4qnikAnrfJJMs%3D&st=2018-04-09T16%3A30%3A31Z&se=2018-05-10T16%3A35%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Retriggering the build

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/pullClient.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullClient.md) | :white_check_mark:Succeeded | |
[dsc/pullClientConfigID.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullClientConfigID.md) | :white_check_mark:Succeeded | |
[dsc/pullClientConfigNames.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullClientConfigNames.md) | :white_check_mark:Succeeded | |
[dsc/pullServer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullServer.md) | :white_check_mark:Succeeded | |
[dsc/pullServerSMB.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullServerSMB.md) | :white_check_mark:Succeeded | |
[dsc/registryResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/registryResource.md) | :white_check_mark:Succeeded | |
[dsc/reportServer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/reportServer.md) | :white_check_mark:Succeeded | |
[dsc/secureServer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/secureServer.md) | :white_check_mark:Succeeded | |
[gallery/TOC.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/TOC.yml) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_gdpr_dsr.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_gdpr_dsr.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Core/Receive-Job.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Core/Receive-Job.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md) | :white_check_mark:Succeeded | |
[reference/3.0/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/3.0/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Core/Receive-Job.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Core/Receive-Job.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md) | :white_check_mark:Succeeded | |
[reference/4.0/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/4.0/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Core/Receive-Job.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Core/Receive-Job.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Utility/ConvertFrom-Json.md) | :white_check_mark:Succeeded | |
[reference/5.0/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.0/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Core/Receive-Job.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/Receive-Job.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Security/Protect-CmsMessage.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Security/Protect-CmsMessage.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/ConvertFrom-Json.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | |
[reference/5.1/PowershellGet/Install-Script.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/PowershellGet/Install-Script.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Comment_Based_Help.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Core/Receive-Job.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/Receive-Job.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/ConvertFrom-Json.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Invoke-WebRequest.md) | :white_check_mark:Succeeded | |
[reference/6/Microsoft.PowerShell.Utility/Set-Variable.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Utility/Set-Variable.md) | :white_check_mark:Succeeded | |
[reference/6/PackageManagement/Register-PackageSource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PackageManagement/Register-PackageSource.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/PowerShell-Core-on-ARM.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/PowerShell-Core-on-ARM.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS-and-Linux.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS-and-Linux.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/toc.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/toc.yml) | :white_check_mark:Succeeded | |
[wmf/5.0/feedback_moduleversionranges.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/wmf/5.0/feedback_moduleversionranges.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201804092234576295-2319%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aCEa%2BOxNDQTYnxcbM1AT18uiM%2F1o9TUoRcRx%2Bw0uLZw%3D&st=2018-04-09T22%3A39%3A21Z&se=2018-05-10T22%3A44%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
