### PR TITLE
Merging latest changes into Live

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/PowerShell/PowerShell-Docs, working directory: W:\hzbs-s, target branch: live, target branch commit: 12dceada70280f96eaeab9714d72957d1a7f7468, source branch: staging, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801170042497231-2063%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=k%2Fuir1yz0sw3gHzdOV42q0II5Si1z%2Fo6MArMeHXTh6c%3D&st=2018-01-17T00%3A38%3A26Z&se=2018-02-17T00%3A43%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/PowerShell/PowerShell-Docs, working directory: W:\zach-s, target branch: live, target branch commit: 12dceada70280f96eaeab9714d72957d1a7f7468, source branch: staging, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801170211094652-2063%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tOJyr4Wl7UKgeq%2BpO6sA8j%2FkS18LpYmJk%2BvW4b5UEfI%3D&st=2018-01-17T02%3A06%3A49Z&se=2018-02-17T02%3A11%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Close/Reopen to try again.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/PowerShell/PowerShell-Docs, working directory: W:\hy4h-s, target branch: live, target branch commit: 12dceada70280f96eaeab9714d72957d1a7f7468, source branch: staging, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801170212341641-2063%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2QfOJxH0rHn0F%2FqL%2FmSyishvBcG4bmgej8EoWRk8V1o%3D&st=2018-01-17T02%3A08%3A11Z&se=2018-02-17T02%3A13%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/DSCAutomationHostEnabled.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/DSCAutomationHostEnabled.md) | :warning:Warning | | [Details](#user-content-dsc%2FDSCAutomationHostEnabled.md)
[dsc/DscForEngineers.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/DscForEngineers.md) | :warning:Warning | | [Details](#user-content-dsc%2FDscForEngineers.md)
[dsc/PackageManagementDscResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/PackageManagementDscResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FPackageManagementDscResource.md)
[dsc/PackageManagementSourceDscResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/PackageManagementSourceDscResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FPackageManagementSourceDscResource.md)
[dsc/archiveResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/archiveResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FarchiveResource.md)
[dsc/authoringResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FauthoringResource.md)
[dsc/authoringResourceClass.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceClass.md) | :warning:Warning | | [Details](#user-content-dsc%2FauthoringResourceClass.md)
[dsc/authoringResourceComposite.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceComposite.md) | :warning:Warning | | [Details](#user-content-dsc%2FauthoringResourceComposite.md)
[dsc/authoringResourceMOF.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMOF.md) | :warning:Warning | | [Details](#user-content-dsc%2FauthoringResourceMOF.md)
[dsc/authoringResourceMofCS.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofCS.md) | :warning:Warning | | [Details](#user-content-dsc%2FauthoringResourceMofCS.md)
[dsc/authoringResourceMofDesigner.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofDesigner.md) | :warning:Warning | | [Details](#user-content-dsc%2FauthoringResourceMofDesigner.md)
[dsc/azureDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/azureDsc.md) | :warning:Warning | | [Details](#user-content-dsc%2FazureDsc.md)
[dsc/bootstrapDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/bootstrapDsc.md) | :warning:Warning | | [Details](#user-content-dsc%2FbootstrapDsc.md)
[dsc/builtInResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/builtInResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FbuiltInResource.md)
[dsc/compositeConfigs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/compositeConfigs.md) | :warning:Warning | | [Details](#user-content-dsc%2FcompositeConfigs.md)
[dsc/configData.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configData.md) | :warning:Warning | | [Details](#user-content-dsc%2FconfigData.md)
[dsc/configDataCredentials.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configDataCredentials.md) | :warning:Warning | | [Details](#user-content-dsc%2FconfigDataCredentials.md)
[dsc/configHelp.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configHelp.md) | :warning:Warning | | [Details](#user-content-dsc%2FconfigHelp.md)
[dsc/configurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configurations.md) | :warning:Warning | | [Details](#user-content-dsc%2Fconfigurations.md)
[dsc/crossNodeDependencies.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/crossNodeDependencies.md) | :warning:Warning | | [Details](#user-content-dsc%2FcrossNodeDependencies.md)
[dsc/debugResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/debugResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FdebugResource.md)
[dsc/decisionMaker.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/decisionMaker.md) | :warning:Warning | | [Details](#user-content-dsc%2FdecisionMaker.md)
[dsc/directCallResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/directCallResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FdirectCallResource.md)
[dsc/dscCiCd.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dscCiCd.md) | :warning:Warning | | [Details](#user-content-dsc%2FdscCiCd.md)
[dsc/dscExamples.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dscExamples.md) | :warning:Warning | | [Details](#user-content-dsc%2FdscExamples.md)
[dsc/enactingConfigurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/enactingConfigurations.md) | :warning:Warning | | [Details](#user-content-dsc%2FenactingConfigurations.md)
[dsc/environmentResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/environmentResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FenvironmentResource.md)
[dsc/fileResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/fileResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FfileResource.md)
[dsc/gettingStarted.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/gettingStarted.md) | :warning:Warning | | [Details](#user-content-dsc%2FgettingStarted.md)
[dsc/groupSetResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/groupSetResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FgroupSetResource.md)
[dsc/lnxArchiveResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxArchiveResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxArchiveResource.md)
[dsc/lnxBuiltInResources.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxBuiltInResources.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxBuiltInResources.md)
[dsc/lnxEnvironmentResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxEnvironmentResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxEnvironmentResource.md)
[dsc/lnxFileLineResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxFileLineResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxFileLineResource.md)
[dsc/lnxFileResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxFileResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxFileResource.md)
[dsc/lnxGettingStarted.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxGettingStarted.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxGettingStarted.md)
[dsc/lnxGroupResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxGroupResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxGroupResource.md)
[dsc/lnxPackageResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxPackageResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxPackageResource.md)
[dsc/lnxScriptResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxScriptResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxScriptResource.md)
[dsc/lnxServiceResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxServiceResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxServiceResource.md)
[dsc/lnxSshAuthorizedKeysResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxSshAuthorizedKeysResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxSshAuthorizedKeysResource.md)
[dsc/lnxUserResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxUserResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlnxUserResource.md)
[dsc/logResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/logResource.md) | :warning:Warning | | [Details](#user-content-dsc%2FlogResource.md)
[dsc/metaConfig.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/metaConfig.md) | :warning:Warning | | [Details](#user-content-dsc%2FmetaConfig.md)
[dsc/metaConfig4.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/metaConfig4.md) | :warning:Warning | | [Details](#user-content-dsc%2FmetaConfig4.md)
[dsc/msft-dsclocalconfigurationmanager-applyconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-applyconfiguration.md) | :warning:Warning | | [Details](#user-content-dsc%2Fmsft-dsclocalconfigurationmanager-applyconfiguration.md)
[dsc/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md) | :warning:Warning | | [Details](#user-content-dsc%2Fmsft-dsclocalconfigurationmanager-disabledebugconfiguration.md)
[dsc/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md) | :warning:Warning | | [Details](#user-content-dsc%2Fmsft-dsclocalconfigurationmanager-enabledebugconfiguration.md)
[dsc/msft-dsclocalconfigurationmanager-getconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-getconfiguration.md) | :warning:Warning | | [Details](#user-content-dsc%2Fmsft-dsclocalconfigurationmanager-getconfiguration.md)
[dsc/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md) | :warning:Warning | | [Details](#user-content-dsc%2Fmsft-dsclocalconfigurationmanager-getconfigurationresultoutput.md)

This comment lists only the first 50 files in the pull request.
<a name="dsc%2FDSCAutomationHostEnabled.md"></a>
### [dsc/DSCAutomationHostEnabled.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/DSCAutomationHostEnabled.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FDscForEngineers.md"></a>
### [dsc/DscForEngineers.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/DscForEngineers.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FPackageManagementDscResource.md"></a>
### [dsc/PackageManagementDscResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/PackageManagementDscResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FPackageManagementSourceDscResource.md"></a>
### [dsc/PackageManagementSourceDscResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/PackageManagementSourceDscResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FarchiveResource.md"></a>
### [dsc/archiveResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/archiveResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FauthoringResource.md"></a>
### [dsc/authoringResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FauthoringResourceClass.md"></a>
### [dsc/authoringResourceClass.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceClass.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FauthoringResourceComposite.md"></a>
### [dsc/authoringResourceComposite.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceComposite.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FauthoringResourceMOF.md"></a>
### [dsc/authoringResourceMOF.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMOF.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FauthoringResourceMofCS.md"></a>
### [dsc/authoringResourceMofCS.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofCS.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FauthoringResourceMofDesigner.md"></a>
### [dsc/authoringResourceMofDesigner.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofDesigner.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FazureDsc.md"></a>
### [dsc/azureDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/azureDsc.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FbootstrapDsc.md"></a>
### [dsc/bootstrapDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/bootstrapDsc.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FbuiltInResource.md"></a>
### [dsc/builtInResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/builtInResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FcompositeConfigs.md"></a>
### [dsc/compositeConfigs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/compositeConfigs.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FconfigData.md"></a>
### [dsc/configData.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configData.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FconfigDataCredentials.md"></a>
### [dsc/configDataCredentials.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configDataCredentials.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FconfigHelp.md"></a>
### [dsc/configHelp.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configHelp.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2Fconfigurations.md"></a>
### [dsc/configurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configurations.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FcrossNodeDependencies.md"></a>
### [dsc/crossNodeDependencies.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/crossNodeDependencies.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FdebugResource.md"></a>
### [dsc/debugResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/debugResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FdecisionMaker.md"></a>
### [dsc/decisionMaker.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/decisionMaker.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FdirectCallResource.md"></a>
### [dsc/directCallResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/directCallResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FdscCiCd.md"></a>
### [dsc/dscCiCd.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dscCiCd.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FdscExamples.md"></a>
### [dsc/dscExamples.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/dscExamples.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FenactingConfigurations.md"></a>
### [dsc/enactingConfigurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/enactingConfigurations.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FenvironmentResource.md"></a>
### [dsc/environmentResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/environmentResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FfileResource.md"></a>
### [dsc/fileResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/fileResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FgettingStarted.md"></a>
### [dsc/gettingStarted.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/gettingStarted.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FgroupSetResource.md"></a>
### [dsc/groupSetResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/groupSetResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxArchiveResource.md"></a>
### [dsc/lnxArchiveResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxArchiveResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxBuiltInResources.md"></a>
### [dsc/lnxBuiltInResources.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxBuiltInResources.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxEnvironmentResource.md"></a>
### [dsc/lnxEnvironmentResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxEnvironmentResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxFileLineResource.md"></a>
### [dsc/lnxFileLineResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxFileLineResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxFileResource.md"></a>
### [dsc/lnxFileResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxFileResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxGettingStarted.md"></a>
### [dsc/lnxGettingStarted.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxGettingStarted.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxGroupResource.md"></a>
### [dsc/lnxGroupResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxGroupResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxPackageResource.md"></a>
### [dsc/lnxPackageResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxPackageResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxScriptResource.md"></a>
### [dsc/lnxScriptResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxScriptResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxServiceResource.md"></a>
### [dsc/lnxServiceResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxServiceResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxSshAuthorizedKeysResource.md"></a>
### [dsc/lnxSshAuthorizedKeysResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxSshAuthorizedKeysResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlnxUserResource.md"></a>
### [dsc/lnxUserResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxUserResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FlogResource.md"></a>
### [dsc/logResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/logResource.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FmetaConfig.md"></a>
### [dsc/metaConfig.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/metaConfig.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2FmetaConfig4.md"></a>
### [dsc/metaConfig4.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/metaConfig4.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2Fmsft-dsclocalconfigurationmanager-applyconfiguration.md"></a>
### [dsc/msft-dsclocalconfigurationmanager-applyconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-applyconfiguration.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2Fmsft-dsclocalconfigurationmanager-disabledebugconfiguration.md"></a>
### [dsc/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-disabledebugconfiguration.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2Fmsft-dsclocalconfigurationmanager-enabledebugconfiguration.md"></a>
### [dsc/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-enabledebugconfiguration.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2Fmsft-dsclocalconfigurationmanager-getconfiguration.md"></a>
### [dsc/msft-dsclocalconfigurationmanager-getconfiguration.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-getconfiguration.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

<a name="dsc%2Fmsft-dsclocalconfigurationmanager-getconfigurationresultoutput.md"></a>
### [dsc/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-getconfigurationresultoutput.md)
 - **[Warning]** Can&#39;t find output file for bread/toc.json

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801170213127196-2063%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cbhKV7%2BpJr64%2BBaHCQUz3nOhDqRAL3pcQ%2B5DDer9Qnw%3D&st=2018-01-17T02%3A36%3A08Z&se=2018-02-17T02%3A41%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
