### PR TITLE
Made New-ExternalHelp cmdlet warnings into terminating errors

### PR DESCRIPTION
**Pull request by HemantMahawar**
- Also added bunch of comments in the code :)

### CODE REVIEW

**Comment by HemantMahawar** [comment]
@joeyaiello need your LGTM before merge :)

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701140039547106-952%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701170213171157-952%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@JoeyAiello, your silence has been taken as LGTM ;)

**Comment by joeyaiello** [comment]
<24 hours?! Cmonnnn... ;)

**Pull request merged**
