### PR TITLE
Update information on here-string closing quotation mark indentation.

### LINKED ISSUE #2471: Update documentation on here-string closing quotation mark indentation.
Documentation update for PowerShell/PowerShell#6923.

Issue Details
-----------------

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

### PR DESCRIPTION
**Pull request by sethvs**
Fix #2471 

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [x] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md](https://github.com/sethvs/PowerShell-Docs/blob/hereString/reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Quoting_Rules.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Quoting_Rules.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md](https://github.com/sethvs/PowerShell-Docs/blob/hereString/reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805251317047553-2472%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wh9cZGMA%2F%2BTcmoLRgS5HzH2ISASGUJOUX8FobwGCLiA%3D&st=2018-05-25T13%3A21%3A15Z&se=2018-06-25T13%3A26%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md](https://github.com/sethvs/PowerShell-Docs/blob/hereString/reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Quoting_Rules.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_Quoting_Rules.md"></a>
### [reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md](https://github.com/sethvs/PowerShell-Docs/blob/hereString/reference/6/Microsoft.PowerShell.Core/About/about_Quoting_Rules.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805251317177039-2472%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jYEJCrjh0f5S3ZyjjI0uyGYugtRyytrNY1OJ6rVbJeI%3D&st=2018-05-25T13%3A30%3A12Z&se=2018-06-25T13%3A35%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@SteveL-MSFT Please review. This PR is targeted for v6.1. Is this a new behavior for here-strings?

**Comment by SteveL-MSFT** [comment]
@sdwheeler waiting on PR to merge which is waiting on @PowerShell/powershell-committee to review (tomorrow)

**Comment by sethvs** [comment]
Closing.

**Pull request closed without merging**
