### PR TITLE
Update Copy-Item.md

### PR DESCRIPTION
**Pull request by doctordns**
1. Added -Recurse to example 11 to resolve issue #2189.
2. Fixed a syntax error at end of the sentence.
3. Added 'powershell' to the markup for each of the examples
4. Remove future tense to improve readability.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### CODE REVIEW

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 108**: **[Error]** Restore nuget package W:\llmh-s\.optemp\dependentPackages\Microsoft.OpenPublishing.CommonPlugins\packages.config in folder:W:\llmh-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error:  Errors in packages.config projects     Unable to find version &#39;1.0.120-alpha&#39; of package &#39;Microsoft.OpenPublishing.CommonPlugins&#39;.       D:\Windows\system32\config\systemprofile\.nuget\packages\: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.120-alpha&#39; is not found on source &#39;D:\Windows\system32\config\systemprofile\.nuget\packages\&#39;.       https://www.myget.org/F/op-dev/api/v2: Package &#39;Microsoft.OpenPublishing.CommonPlugins.1.0.120-alpha&#39; is not found on source &#39;https://www.myget.org/F/op-dev/api/v2&#39;.
 - **Line 290**: **[Error]** Restore dependent packages failed

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805021350496616-2389%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ocVUYZqcU2z31kcNVssE0nuD97jkk0oLw6VtJEM39e4%3D&st=2018-05-02T13%3A46%3A38Z&se=2018-06-02T13%3A51%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Close and reopen to retrigger the build.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Management/Copy-Item.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-8/reference/6/Microsoft.PowerShell.Management/Copy-Item.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805021435030576-2389%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=UPX6J23hnYzvaaS8t5bEAJF0v4gIS6Ze3nPTcuv79FU%3D&st=2018-05-02T14%3A38%3A55Z&se=2018-06-02T14%3A43%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Management/Copy-Item.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-8/reference/6/Microsoft.PowerShell.Management/Copy-Item.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C2%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805021624341318-2389%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PIJavwyjNmdGIEOn3t6nirK8gBP7HQZ92P%2BXSLw8qwQ%3D&st=2018-05-02T16%3A28%3A55Z&se=2018-06-02T16%3A33%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
