### PR TITLE
Revert "fix overaggressive codeblocks"

### PR DESCRIPTION
**Pull request by zjalexander**
Reverts PowerShell/PowerShell-Docs#810

### CODE REVIEW

**Comment by vors** [comment]
Thank you, Zach!

I will try to make appveyor build fail, if there are problem in the schema.
Currently it doesn't.

**Comment by zjalexander** [comment]
@vors you read my mind! :)

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/PowerShell/PowerShell-Docs/blob/revert-810-zjalexander-patch-2/reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | | [Details](#user-content-reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611180127277522-820%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by vors** [comment]
@zjalexander done! #822 together with #821 these two PRs should make everything vigorous.

**Pull request merged**
