### PR TITLE
Fix #3312

### LINKED ISSUE #3312: Missing image
In the section Multiple Parameter Sets in https://docs.microsoft.com/en-us/powershell/developer/cmdlet/cmdlet-parameter-sets , it says: "In the following illustration, the left column shows..."; however, there is no illustration on the page.

### PR DESCRIPTION
**Pull request by matt9ucci**
Fixed #3312 probably  :sweat_smile:

The relative path looks correct. It seems that the markdown format is incorrect. I followed the markdown format of [using-vscode.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/vscode/using-vscode.md) that can shows an image like [this](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/vscode/using-vscode?view=powershell-6).

### CODE REVIEW

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/cmdlet/cmdlet-parameter-sets.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-3312/developer/cmdlet/cmdlet-parameter-sets.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/cmdlet-parameter-sets?branch=pr-en-us-3324) | [Details](#user-content-developer%2Fcmdlet%2Fcmdlet-parameter-sets.md)

<a name="developer%2Fcmdlet%2Fcmdlet-parameter-sets.md"></a>
### [developer/cmdlet/cmdlet-parameter-sets.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-3312/developer/cmdlet/cmdlet-parameter-sets.md)
 - **Line 28**: **[Warning]** Invalid file link:(~/media/ps-parametersets.gif).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201811221033576910-3324%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pb8IG5C4KCtC1fKyNZHnVsA0opxgI8cU7G35PzR7R4Q%3D&st=2018-11-22T10%3A42%3A42Z&se=2018-12-23T10%3A47%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@matt9ucci The change you made is correct but the link is still broken. This is a configuration problem in the docfx.json. I am fixing that in another PR. When that completes I can trigger a rebuild for your PR.

**Comment by sdwheeler** [comment]
Retriggering the build

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[developer/cmdlet/cmdlet-parameter-sets.md](https://github.com/matt9ucci/PowerShell-Docs/blob/patch-3312/developer/cmdlet/cmdlet-parameter-sets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/developer/cmdlet/cmdlet-parameter-sets?branch=pr-en-us-3324) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201811231741401141-3324%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Ss6o00mhyH8efo0a%2FGG31KYAWmWHTfJqxN9RoYLpHfQ%3D&st=2018-11-23T17%3A50%3A40Z&se=2018-12-24T17%3A55%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
