### PR TITLE
Fixing code format and removing passive voice

### PR DESCRIPTION
**Pull request by tysonjhayes**
Went to fix the the formatting in the code examples and removed the passive voice while I was at it, can roll back if this is not wanted.

### CODE REVIEW

**Comment by tysonjhayes** [comment]
I'm not sure what it's telling me here, could anyone help me out?

**Comment by eslesar** [comment]
If you are referring to the "All checks have failed" message--this is about the build system. This is usually fixed very quickly, and a clean build isn't a requirement unless checking in to the live branch.

**Comment by tysonjhayes** [comment]
@eslesar - so do I need to do anything or is this acceptable for someone attempting to merge?

**Comment by eslesar** [comment]
This is acceptable. I will merge it later today.

**Pull request merged**
