### PR TITLE
Document removal of `Persist` parameter from `New-PSDrive` on UNIX

### LINKED ISSUE #3316: Document removal of `-Persist` from `New-PSDrive` on non-Windows platforms
Issue Details
-----------------
https://github.com/PowerShell/PowerShell/pull/8291 will remove `-Persist` from `New-PSDrive` on non-Windows platforms because `-Persist` is only supported on Windows. 

An extra line in the docs for the `Persist` parameter like "This parameter is only available on Windows." would be nice.

I'm happy to submit a PR for this. 

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

### PR DESCRIPTION
**Pull request by lukexjeremy**
The `Persist` parameter of `New-PSDrive` is only supported on Windows. Persist will be removed on UNIX by https://github.com/PowerShell/PowerShell/pull/8291. Add this information to the documentation of the `Persist` parameter.

Fix #3316.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [x] The documented feature was introduced in version 6.2 of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by lukexjeremy** [comment]
I'm not sure how to fix the build error. 

The build error is *The process cannot access the file 'W:\slcf-log-32422643\report.txt' because it is being used by another process.*

There is a [link in the build report](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) to fix it, but I get a permissions error when I try to login. 

It seems unrelated to my change. Is it OK to make an empty commit to trigger the build again?

**Comment by sdwheeler** [comment]
Retriggering the build

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in http://SiteHelp and include the error report for our team to troubleshoot

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201811220435148034-3320%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4kKWy7KQ5Z6jZsipH%2BB829N%2Bh2Brc5VlBce%2BWWDahB4%3D&st=2018-11-22T04%3A31%3A13Z&se=2018-12-23T04%3A36%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Forces a republish of the branch to see if that will fix the build error.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/Microsoft.PowerShell.Management/New-WebServiceProxy.md](https://github.com/lukexjeremy/PowerShell-Docs/blob/persist-newpsdrive-windows-only/reference/5.0/Microsoft.PowerShell.Management/New-WebServiceProxy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/new-webserviceproxy?view=powershell-5.0&branch=pr-en-us-3320) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md](https://github.com/lukexjeremy/PowerShell-Docs/blob/persist-newpsdrive-windows-only/reference/5.1/Microsoft.PowerShell.Management/New-WebServiceProxy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/new-webserviceproxy?view=powershell-5.1&branch=pr-en-us-3320) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Management/New-PSDrive.md](https://github.com/lukexjeremy/PowerShell-Docs/blob/persist-newpsdrive-windows-only/reference/6/Microsoft.PowerShell.Management/New-PSDrive.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.management/new-psdrive?view=powershell-6&branch=pr-en-us-3320) (powershell-6) |
[reference/6/Microsoft.PowerShell.Utility/Write-Information.md](https://github.com/lukexjeremy/PowerShell-Docs/blob/persist-newpsdrive-windows-only/reference/6/Microsoft.PowerShell.Utility/Write-Information.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/write-information?view=powershell-6&branch=pr-en-us-3320) (powershell-6) |
[reference/docs-conceptual/getting-started/fundamental/Learning-PowerShell-Names.md](https://github.com/lukexjeremy/PowerShell-Docs/blob/persist-newpsdrive-windows-only/reference/docs-conceptual/getting-started/fundamental/Learning-PowerShell-Names.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/fundamental/learning-powershell-names?view=powershell-3.0&branch=pr-en-us-3320) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/fundamental/learning-powershell-names?view=powershell-4.0&branch=pr-en-us-3320) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/fundamental/learning-powershell-names?view=powershell-5.0&branch=pr-en-us-3320) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/fundamental/learning-powershell-names?view=powershell-5.1&branch=pr-en-us-3320) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/fundamental/learning-powershell-names?view=powershell-6&branch=pr-en-us-3320) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201811231750164031-3320%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zZ00ho4hIQFb1s4FFCkZWHZPvPZ2fv450AQwoDxEtR8%3D&st=2018-11-23T17%3A59%3A33Z&se=2018-12-24T18%3A04%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
