### PR TITLE
updated blog links to reduce redirects

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/getting-started/more-powershell-learning.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2902/reference/docs-conceptual/getting-started/more-powershell-learning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-3.0&branch=pr-en-us-2931) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-4.0&branch=pr-en-us-2931) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-5.0&branch=pr-en-us-2931) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-5.1&branch=pr-en-us-2931) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-6&branch=pr-en-us-2931) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201809181914165552-2931%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jk14ZGzUkRn0e%2FHGgpUp6IhY0Km4T0OIzWIExEKXMIw%3D&st=2018-09-18T19%3A27%3A07Z&se=2018-10-19T19%3A32%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
#sign-off

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/getting-started/more-powershell-learning.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue2902/reference/docs-conceptual/getting-started/more-powershell-learning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-3.0&branch=pr-en-us-2931) (powershell-3.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-4.0&branch=pr-en-us-2931) (powershell-4.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-5.0&branch=pr-en-us-2931) (powershell-5.0)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-5.1&branch=pr-en-us-2931) (powershell-5.1)<br/> [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/getting-started/more-powershell-learning?view=powershell-6&branch=pr-en-us-2931) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201809181935092475-2931%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HRNkm5EPvznTj2D6GNbyGzgBhoZpq2dfGP6pDdT69fE%3D&st=2018-09-18T19%3A51%3A47Z&se=2018-10-19T19%3A56%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
#sign-off LGTM

**Pull request merged**
