### PR TITLE
Update yml to have staging and live deploy

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Experimenting with deploying to staging and production for staging and live branches.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702082318016917-1021%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702082342037957-1021%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C9%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702090001224113-1021%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by adityapatwardhan** [comment]
This is now ready to merge.

**Pull request merged**
