### PR TITLE
Adding PackageManagement DSC resource docs

### PR DESCRIPTION
**Pull request by brywang-msft**
Adding PackageManagement DSC resource docs for DSC resources that will ship with the PackageManagement module in RS2+. Also available from OSS,
from a different module until RS2 changes are ported to OSS.

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[dsc/PackageManagementDscResource.md](https://github.com/brywang-msft/PowerShell-Docs/blob/staging/dsc/PackageManagementDscResource.md) | :x:Error | | [Details](#user-content-dsc/PackageManagementDscResource.md)
[dsc/PackageManagementSourceDscResource.md](https://github.com/brywang-msft/PowerShell-Docs/blob/staging/dsc/PackageManagementSourceDscResource.md) | :x:Error | | [Details](#user-content-dsc/PackageManagementSourceDscResource.md)

<a name="dsc/PackageManagementDscResource.md"></a>
### [dsc/PackageManagementDscResource.md](https://github.com/brywang-msft/PowerShell-Docs/blob/staging/dsc/PackageManagementDscResource.md)
 - **Line unspecified**: **[Error]** Author jianyunt,brywang,keithb cannot be recognized in GitHub.

<a name="dsc/PackageManagementSourceDscResource.md"></a>
### [dsc/PackageManagementSourceDscResource.md](https://github.com/brywang-msft/PowerShell-Docs/blob/staging/dsc/PackageManagementSourceDscResource.md)
 - **Line unspecified**: **[Error]** Author jianyunt,brywang,keithb cannot be recognized in GitHub.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612231915081227-922%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612231922298814-922%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C23%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612231927581873-922%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by brywang-msft** [comment]
Sent this PR before linking GitHub account with internal alias. Not sure if you want me to add the cla-not-required label myself.

**Pull request merged**
