### PR TITLE
Wide metadata tags update

### PR DESCRIPTION
**Pull request by juanpablojofre**

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612122212027969-898%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612131849190873-898%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@eslesar, whenever you have a minute... would you please check this PR?

I fixed the appveyor build error.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C12%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201612132222037387-898%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
