### PR TITLE
Merging latest changes to live

### PR DESCRIPTION
**Pull request by sdwheeler**

### CODE REVIEW

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 16**: **[Error]** Restore nuget package W:\lwgj-s\.optemp\packages\opbuild.scripts.1.45.0\tools\packages.config in folder:W:\lwgj-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error: The operation has timed out

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201803142055048039-2178%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=uN3hrKxxMdIAM5zf3YRuN4a83QlDDR9moXeLT7QFD9U%3D&st=2018-03-14T21%3A02%3A24Z&se=2018-04-14T21%3A07%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 16**: **[Error]** Restore nuget package W:\txmh-s\.optemp\packages\opbuild.scripts.1.45.0\tools\packages.config in folder:W:\txmh-s\.optemp\packages failed, possibly due to transient errors from nuget servers. Please retry building your content. If the issue still happens, open a ticket in http://SiteHelp. Detailed error: The operation has timed out

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201803142140239444-2178%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=OBVHXq%2FD7krRoDPver4mhY9Q%2F0vR7H%2FsvzXG%2BBhS%2FSE%3D&st=2018-03-14T21%3A44%3A32Z&se=2018-04-14T21%3A49%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
Close and reopen to retrigger build.

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/core-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fcore-powershell%2Fise%2FHow-to-Debug-Scripts-in-Windows-PowerShell-ISE.md)
[reference/docs-conceptual/core-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fcore-powershell%2Fise%2FHow-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md)
[reference/docs-conceptual/core-powershell/ise/The-ISESnippetObject.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/ise/The-ISESnippetObject.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fcore-powershell%2Fise%2FThe-ISESnippetObject.md)
[reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md)
[reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fwhats-new%2FWhat-s-New-in-the-PowerShell-50-ISE.md)
[README.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/README.md) | :white_check_mark:Succeeded | |
[dsc/TOC.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/TOC.md) | :white_check_mark:Succeeded | |
[dsc/TOC.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/TOC.yml) | :white_check_mark:Succeeded | |
[dsc/authoringResourceClass.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceClass.md) | :white_check_mark:Succeeded | |
[dsc/authoringResourceMofCS.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofCS.md) | :white_check_mark:Succeeded | |
[dsc/authoringResourceMofDesigner.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofDesigner.md) | :white_check_mark:Succeeded | |
[dsc/azureDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/azureDsc.md) | :white_check_mark:Succeeded | |
[dsc/azureDscexthistory.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/azureDscexthistory.md) | :white_check_mark:Succeeded | |
[dsc/bootstrapDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/bootstrapDsc.md) | :white_check_mark:Succeeded | |
[dsc/configDataCredentials.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configDataCredentials.md) | :white_check_mark:Succeeded | |
[dsc/configHelp.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configHelp.md) | :white_check_mark:Succeeded | |
[dsc/configurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configurations.md) | :white_check_mark:Succeeded | |
[dsc/debugResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/debugResource.md) | :white_check_mark:Succeeded | |
[dsc/decisionMaker.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/decisionMaker.md) | :white_check_mark:Succeeded | |
[dsc/directCallResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/directCallResource.md) | :white_check_mark:Succeeded | |
[dsc/docfx.json](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/docfx.json) | :white_check_mark:Succeeded | |
[dsc/enactingConfigurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/enactingConfigurations.md) | :white_check_mark:Succeeded | |
[dsc/gettingStarted.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/gettingStarted.md) | :white_check_mark:Succeeded | |
[dsc/lnxFileResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxFileResource.md) | :white_check_mark:Succeeded | |
[dsc/msft-dsclocalconfigurationmanager-resourceget.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-resourceget.md) | :white_check_mark:Succeeded | |
[dsc/msft-dsclocalconfigurationmanager-resourceset.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-resourceset.md) | :white_check_mark:Succeeded | |
[dsc/msft-dsclocalconfigurationmanager-resourcetest.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-resourcetest.md) | :white_check_mark:Succeeded | |
[dsc/nanoDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/nanoDsc.md) | :white_check_mark:Succeeded | |
[dsc/partialConfigs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/partialConfigs.md) | :white_check_mark:Succeeded | |
[dsc/pullServerSMB.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullServerSMB.md) | :white_check_mark:Succeeded | |
[dsc/reportServer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/reportServer.md) | :white_check_mark:Succeeded | |
[dsc/runAsUser.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/runAsUser.md) | :white_check_mark:Succeeded | |
[dsc/scriptResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/scriptResource.md) | :white_check_mark:Succeeded | |
[dsc/secureMOF.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/secureMOF.md) | :white_check_mark:Succeeded | |
[dsc/secureServer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/secureServer.md) | :white_check_mark:Succeeded | |
[dsc/separatingEnvData.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/separatingEnvData.md) | :white_check_mark:Succeeded | |
[dsc/serviceSetResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/serviceSetResource.md) | :white_check_mark:Succeeded | |
[dsc/sxsResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/sxsResource.md) | :white_check_mark:Succeeded | |
[dsc/troubleshooting.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/troubleshooting.md) | :white_check_mark:Succeeded | |
[dsc/waitForAllResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/waitForAllResource.md) | :white_check_mark:Succeeded | |
[dsc/waitForAnyResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/waitForAnyResource.md) | :white_check_mark:Succeeded | |
[dsc/waitForSomeResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/waitForSomeResource.md) | :white_check_mark:Succeeded | |
[gallery/TOC.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/TOC.md) | :white_check_mark:Succeeded | |
[gallery/TOC.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/TOC.yml) | :white_check_mark:Succeeded | |
[gallery/docfx.json](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/docfx.json) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_ItemManifestAffectingUI.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_ItemManifestAffectingUI.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_creating_an_account.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_creating_an_account.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_deploy_to_azure_automation.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_deploy_to_azure_automation.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_deploy_to_azure_automation_requireLicenseAcceptance.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_deploy_to_azure_automation_requireLicenseAcceptance.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
<a name="reference%2Fdocs-conceptual%2Fcore-powershell%2Fise%2FHow-to-Debug-Scripts-in-Windows-PowerShell-ISE.md"></a>
### [reference/docs-conceptual/core-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/ise/How-to-Debug-Scripts-in-Windows-PowerShell-ISE.md)
 - **Line 178**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 178**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 178**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 178**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 178**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).

<a name="reference%2Fdocs-conceptual%2Fcore-powershell%2Fise%2FHow-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md"></a>
### [reference/docs-conceptual/core-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/ise/How-to-Write-and-Run-Scripts-in-the-Windows-PowerShell-ISE.md)
 - **Line 138**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 138**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 138**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 138**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 138**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).

<a name="reference%2Fdocs-conceptual%2Fcore-powershell%2Fise%2FThe-ISESnippetObject.md"></a>
### [reference/docs-conceptual/core-powershell/ise/The-ISESnippetObject.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/core-powershell/ise/The-ISESnippetObject.md)
 - **Line 49**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/The-Windows-PowerShell-ISE-Scripting-Object-Model.md).
 - **Line 49**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/The-Windows-PowerShell-ISE-Scripting-Object-Model.md).
 - **Line 49**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/The-Windows-PowerShell-ISE-Scripting-Object-Model.md).
 - **Line 49**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/The-Windows-PowerShell-ISE-Scripting-Object-Model.md).
 - **Line 49**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/The-Windows-PowerShell-ISE-Scripting-Object-Model.md).
 - **Line 50**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Windows-PowerShell-ISE-Object-Model-Reference.md).
 - **Line 50**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Windows-PowerShell-ISE-Object-Model-Reference.md).
 - **Line 50**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Windows-PowerShell-ISE-Object-Model-Reference.md).
 - **Line 50**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Windows-PowerShell-ISE-Object-Model-Reference.md).
 - **Line 50**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Windows-PowerShell-ISE-Object-Model-Reference.md).

<a name="reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md"></a>
### [reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md)
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).

<a name="reference%2Fdocs-conceptual%2Fwhats-new%2FWhat-s-New-in-the-PowerShell-50-ISE.md"></a>
### [reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md)
 - **Line 221**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 221**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 221**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 221**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 221**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201803142232080576-2178%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=gU1fdPDqkkdT%2BGltf5EF03lZdB%2Ffqus93jm7J8u0sao%3D&st=2018-03-14T22%3A57%3A55Z&se=2018-04-14T23%3A02%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md)
[README.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/README.md) | :white_check_mark:Succeeded | |
[dsc/TOC.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/TOC.md) | :white_check_mark:Succeeded | |
[dsc/TOC.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/TOC.yml) | :white_check_mark:Succeeded | |
[dsc/authoringResourceClass.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceClass.md) | :white_check_mark:Succeeded | |
[dsc/authoringResourceMofCS.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofCS.md) | :white_check_mark:Succeeded | |
[dsc/authoringResourceMofDesigner.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/authoringResourceMofDesigner.md) | :white_check_mark:Succeeded | |
[dsc/azureDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/azureDsc.md) | :white_check_mark:Succeeded | |
[dsc/azureDscexthistory.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/azureDscexthistory.md) | :white_check_mark:Succeeded | |
[dsc/bootstrapDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/bootstrapDsc.md) | :white_check_mark:Succeeded | |
[dsc/configDataCredentials.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configDataCredentials.md) | :white_check_mark:Succeeded | |
[dsc/configHelp.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configHelp.md) | :white_check_mark:Succeeded | |
[dsc/configurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/configurations.md) | :white_check_mark:Succeeded | |
[dsc/debugResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/debugResource.md) | :white_check_mark:Succeeded | |
[dsc/decisionMaker.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/decisionMaker.md) | :white_check_mark:Succeeded | |
[dsc/directCallResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/directCallResource.md) | :white_check_mark:Succeeded | |
[dsc/docfx.json](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/docfx.json) | :white_check_mark:Succeeded | |
[dsc/enactingConfigurations.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/enactingConfigurations.md) | :white_check_mark:Succeeded | |
[dsc/gettingStarted.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/gettingStarted.md) | :white_check_mark:Succeeded | |
[dsc/lnxFileResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/lnxFileResource.md) | :white_check_mark:Succeeded | |
[dsc/msft-dsclocalconfigurationmanager-resourceget.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-resourceget.md) | :white_check_mark:Succeeded | |
[dsc/msft-dsclocalconfigurationmanager-resourceset.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-resourceset.md) | :white_check_mark:Succeeded | |
[dsc/msft-dsclocalconfigurationmanager-resourcetest.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/msft-dsclocalconfigurationmanager-resourcetest.md) | :white_check_mark:Succeeded | |
[dsc/nanoDsc.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/nanoDsc.md) | :white_check_mark:Succeeded | |
[dsc/partialConfigs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/partialConfigs.md) | :white_check_mark:Succeeded | |
[dsc/pullServerSMB.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/pullServerSMB.md) | :white_check_mark:Succeeded | |
[dsc/reportServer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/reportServer.md) | :white_check_mark:Succeeded | |
[dsc/runAsUser.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/runAsUser.md) | :white_check_mark:Succeeded | |
[dsc/scriptResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/scriptResource.md) | :white_check_mark:Succeeded | |
[dsc/secureMOF.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/secureMOF.md) | :white_check_mark:Succeeded | |
[dsc/secureServer.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/secureServer.md) | :white_check_mark:Succeeded | |
[dsc/separatingEnvData.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/separatingEnvData.md) | :white_check_mark:Succeeded | |
[dsc/serviceSetResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/serviceSetResource.md) | :white_check_mark:Succeeded | |
[dsc/sxsResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/sxsResource.md) | :white_check_mark:Succeeded | |
[dsc/troubleshooting.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/troubleshooting.md) | :white_check_mark:Succeeded | |
[dsc/waitForAllResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/waitForAllResource.md) | :white_check_mark:Succeeded | |
[dsc/waitForAnyResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/waitForAnyResource.md) | :white_check_mark:Succeeded | |
[dsc/waitForSomeResource.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/dsc/waitForSomeResource.md) | :white_check_mark:Succeeded | |
[gallery/TOC.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/TOC.md) | :white_check_mark:Succeeded | |
[gallery/TOC.yml](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/TOC.yml) | :white_check_mark:Succeeded | |
[gallery/docfx.json](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/docfx.json) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_ItemManifestAffectingUI.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_ItemManifestAffectingUI.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_creating_an_account.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_creating_an_account.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_deploy_to_azure_automation.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_deploy_to_azure_automation.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_deploy_to_azure_automation_requireLicenseAcceptance.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_deploy_to_azure_automation_requireLicenseAcceptance.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_faqs.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_faqs.md) | :white_check_mark:Succeeded | |
[gallery/psgallery/psgallery_gettingstarted.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery_gettingstarted.md) | :white_check_mark:Succeeded | |
[gallery/psget/get_psget_module.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psget/get_psget_module.md) | :white_check_mark:Succeeded | |
[gallery/psget/module/modulewithpseditionsupport.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/gallery/psget/module/modulewithpseditionsupport.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
<a name="reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md"></a>
### [reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md)
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).
 - **Line 147**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/ise/Using-the-Windows-PowerShell-ISE.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201803142321520627-2178%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mQJTVX0v3OA7o9PRp7sgA3G0pu6qGQR6ZXwVCS4Fa1U%3D&st=2018-03-14T23%3A46%3A54Z&se=2018-04-14T23%3A51%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
