### PR TITLE
About_Windows_PowerShell_5.1 #1171

### PR DESCRIPTION
**Pull request by sdwheeler**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [x] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by exchange12rocks** [comment]
I noticed, that you forgot to change the version number in the "SHORT DESCRIPTION" section.

**Comment by sdwheeler** [comment]
@exchange12rocks Thanks. fixed it

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue1171/reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_windows_powershell_5.1.md)

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_windows_powershell_5.1.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue1171/reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801172221378657-2068%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DiOihmiNS1LAt%2F%2BZTpGFgbDxjzVhg22f05BnvzJ6rLE%3D&st=2018-01-17T22%3A43%3A32Z&se=2018-02-17T22%3A48%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue1171/reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_windows_powershell_5.1.md)

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_windows_powershell_5.1.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-issue1171/reference/5.1/Microsoft.PowerShell.Core/About/about_windows_powershell_5.1.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C17%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201801172237257934-2068%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=LblC7kr5qrUXJsxFKO1dBD0yIBFTZ6G1eYDtvF3isjE%3D&st=2018-01-17T23%3A11%3A34Z&se=2018-02-17T23%3A16%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@joeyaiello @zjalexander Please review and merge.

**Pull request merged**
