### PR TITLE
jpjofre-I1403 Conceptual documents cleanup

### PR DESCRIPTION
**Pull request by juanpablojofre**
- Broken links fixed
- Formatting fix
- weird characters removed

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fcore-powershell%2Fweb-access%2Funinstall-windows-powershell-web-access.md)
[reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md)
[reference/docs-conceptual/toc.yml](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/toc.yml) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Ftoc.yml)
[reference/docs-conceptual/PowerShell-Scripting.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/PowerShell-Scripting.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/core-powershell/ise/The-ISEEditor-Object.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/ise/The-ISEEditor-Object.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/basic-cookbooks.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/basic-cookbooks.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/cookbooks/basic-cookbooks-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/cookbooks/basic-cookbooks-reference.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/fundamental/Using-Windows-PowerShell.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/fundamental/Using-Windows-PowerShell.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/more-powershell-learning.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/more-powershell-learning.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/security.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/security.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/whats-new/What-s-New-in-Windows-PowerShell-50.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/whats-new/What-s-New-in-Windows-PowerShell-50.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md) | :white_check_mark:Succeeded | |

<a name="reference%2Fdocs-conceptual%2Fcore-powershell%2Fweb-access%2Funinstall-windows-powershell-web-access.md"></a>
### [reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md)
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).

<a name="reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md"></a>
### [reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md)
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).

<a name="reference%2Fdocs-conceptual%2Ftoc.yml"></a>
### [reference/docs-conceptual/toc.yml](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/toc.yml)
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/setup/security.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/setup/security.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/setup/security.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/setup/security.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/setup/security.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201709131858516292-1654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CPHQl%2Bb8cO9AUY6l2nq8sEAjeY6wE%2FjOd4LK18QocD8%3D&st=2017-09-13T19%3A26%3A36Z&se=2017-09-14T19%3A36%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/toc.yml](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/toc.yml) | :x:Error | | [Details](#user-content-reference%2Fdocs-conceptual%2Ftoc.yml)
[]() | :x:Error | | [Details](#user-content-)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2Fdocs-conceptual%2Ftoc.yml"></a>
### [reference/docs-conceptual/toc.yml](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/toc.yml)
 - **[Error]** W:\kltr-s\reference\docs-conceptual\toc.yml is not a valid TOC File: W:\kltr-s\reference\docs-conceptual\toc.yml is not a valid TOC file.
 - **[Error]** Unable to load file: docs-conceptual/toc.yml via processor: TocDocumentProcessor.

<a name=""></a>
### []()
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** W:\kltr-s\reference\docs-conceptual\toc.yml is not a valid TOC File: W:\kltr-s\reference\docs-conceptual\toc.yml is not a valid TOC file.
 - **Line 81**: **[Error]** W:\kltr-s\.optemp\packages\opbuild.scripts.1.38.3\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_prebuild in the docset PowerShell_PowerShell-docs_reference
 - **[Warning]** &#39;W:\kltr-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\kltr-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **Line 80**: **[Warning]** Failed to run script W:\kltr-s\_dependentPackages\CommonPlugins\tools\PowerShellReference.ps1 with exit code -1

<a name=""></a>
### []()
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** The step SetupFusionToc failed, (Line: 3, Col: 3, Idx: 60) - (Line: 3, Col: 4, Idx: 61): While parsing a block mapping, did not find expected key.
 - **[Error]** W:\kltr-s\reference\docs-conceptual\toc.yml is not a valid TOC File: W:\kltr-s\reference\docs-conceptual\toc.yml is not a valid TOC file.
 - **Line 81**: **[Error]** W:\kltr-s\.optemp\packages\opbuild.scripts.1.38.3\tools\opbuild\plugin.executor.ps1 failed to execute customized script in the plugin step docset_prebuild in the docset PowerShell_PowerShell-docs_reference
 - **[Warning]** &#39;W:\kltr-s\gallery/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **[Warning]** &#39;W:\kltr-s\jea/index.md&#39; would be overwritten by redirection rule configured in master redirection file .openpublishing.redirection.json. Please remove the original file to resolve this warning.
 - **Line 80**: **[Warning]** Failed to run script W:\kltr-s\_dependentPackages\CommonPlugins\tools\PowerShellReference.ps1 with exit code -1

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201709141821056932-1654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nu3Q1osTXFd7K%2Bju9avJ86xRLNiHM32Bi45EQSXwe9c%3D&st=2017-09-14T18%3A22%3A31Z&se=2017-09-15T18%3A32%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fcore-powershell%2Fweb-access%2Funinstall-windows-powershell-web-access.md)
[reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md)
[reference/docs-conceptual/toc.yml](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/toc.yml) | :warning:Warning | | [Details](#user-content-reference%2Fdocs-conceptual%2Ftoc.yml)
[reference/docs-conceptual/PowerShell-Scripting.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/PowerShell-Scripting.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/core-powershell/ise/The-ISEEditor-Object.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/ise/The-ISEEditor-Object.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/workflows/PSWorkflow-Module.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/workflows/PSWorkflowUtility-Module.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/basic-cookbooks.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/basic-cookbooks.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/cookbooks/PowerShellGet-Module.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/cookbooks/basic-cookbooks-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/cookbooks/basic-cookbooks-reference.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/fundamental/Using-Windows-PowerShell.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/fundamental/Using-Windows-PowerShell.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/getting-started/more-powershell-learning.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/getting-started/more-powershell-learning.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/security.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/security.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/setup/setup-reference.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/setup-reference.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/whats-new/What-s-New-in-Windows-PowerShell-50.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/whats-new/What-s-New-in-Windows-PowerShell-50.md) | :white_check_mark:Succeeded | |
[reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/whats-new/What-s-New-in-the-PowerShell-50-ISE.md) | :white_check_mark:Succeeded | |

<a name="reference%2Fdocs-conceptual%2Fcore-powershell%2Fweb-access%2Funinstall-windows-powershell-web-access.md"></a>
### [reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/core-powershell/web-access/uninstall-windows-powershell-web-access.md)
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).
 - **Line 99**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/SecurityNote.jpeg).

<a name="reference%2Fdocs-conceptual%2Fsetup%2FAccessibility-in-Windows-PowerShell-ISE.md"></a>
### [reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/setup/Accessibility-in-Windows-PowerShell-ISE.md)
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).
 - **Line 112**: **[Warning]** Invalid file link:(~/docs-conceptual/core-powershell/web-access/images/Note.jpeg).

<a name="reference%2Fdocs-conceptual%2Ftoc.yml"></a>
### [reference/docs-conceptual/toc.yml](https://github.com/PowerShell/PowerShell-Docs/blob/jpjofre-I1403B/reference/docs-conceptual/toc.yml)
 - **[Warning]** Invalid file link:(~/docs-conceptual/ise/introducing-the-windows-powershell-ise.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/ise/introducing-the-windows-powershell-ise.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/ise/introducing-the-windows-powershell-ise.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/ise/introducing-the-windows-powershell-ise.md).
 - **[Warning]** Invalid file link:(~/docs-conceptual/ise/introducing-the-windows-powershell-ise.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C14%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201709142019250827-1654%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=on0u5qEA4soyagZEONc3Cj0PKCo73ktVpqZB0n2STuI%3D&st=2017-09-14T20%3A45%3A03Z&se=2017-09-15T20%3A55%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Sean ( @sdwheeler ), Eric ( @eslesar ),

If you have a minute, could you please review and merge?

Thanks !!
-- JP

**Pull request merged**
