### PR TITLE
Update release note with DSC-Known issue.

### PR DESCRIPTION
**Pull request by BerheAbrha**
- [ ] Updated release note with DSC-Known issue.

- [ ] Fixed the mark down formatting ( added missing space)

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/known-issues.md](https://github.com/PowerShell/PowerShell-Docs/blob/DSCKnownIssue/wmf/5.1/known-issues.md) | :white_check_mark:Succeeded | | [Details](#user-content-wmf/5.1/known-issues.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611182052473265-825%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by KrishnaV-MSFT** [comment]
@BerheAbrha  The instructions for DSC needed to be run from an elevated PowerShell console right? If so, can you please update.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/known-issues.md](https://github.com/PowerShell/PowerShell-Docs/blob/DSCKnownIssue/wmf/5.1/known-issues.md) | :white_check_mark:Succeeded | | [Details](#user-content-wmf/5.1/known-issues.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611182108169397-825%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[wmf/5.1/known-issues.md](https://github.com/PowerShell/PowerShell-Docs/blob/DSCKnownIssue/wmf/5.1/known-issues.md) | :white_check_mark:Succeeded | | [Details](#user-content-wmf/5.1/known-issues.md)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611182115076904-825%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
