### PR TITLE
Copyedit all versions of ConvertTo-Csv and Export-Csv

### PR DESCRIPTION
**Pull request by davidsmatlak**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Acrolinx scores
ConvertTo-Csv
Original version: 87     
Updated version: 92

Export-Csv
Original version: 87 
Updated version: 93

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fe7e5a6](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/fe7e5a636a6e82267708bc2e1eccd9b3f18bfcfc)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fe7e5a6](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/fe7e5a636a6e82267708bc2e1eccd9b3f18bfcfc)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 21 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[fe7e5a6](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/fe7e5a636a6e82267708bc2e1eccd9b3f18bfcfc)_: 

### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :x:Error | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md)
[reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :x:Error | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md)
[reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :x:Error | | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md)
[reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md) | :x:Error | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md)
[reference/6/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/6/Microsoft.PowerShell.Utility/Export-Csv.md) | :x:Error | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md"></a>
### [reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md)
 - **[Error]** Unable to load file &#39;3.0/Microsoft.PowerShell.Utility/Export-Csv.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :226:(2398) &#39;```powershell
Get-Date | Format-Table -Property D...&#39;
 Expect Heading

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md"></a>
### [reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md)
 - **[Error]** Unable to load file &#39;4.0/Microsoft.PowerShell.Utility/Export-Csv.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :226:(2398) &#39;```powershell
Get-Date | Format-Table -Property D...&#39;
 Expect Heading

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md"></a>
### [reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md)
 - **[Error]** Unable to load file &#39;5.0/Microsoft.PowerShell.Utility/Export-Csv.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :226:(2398) &#39;```powershell
Get-Date | Format-Table -Property D...&#39;
 Expect Heading

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md"></a>
### [reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md)
 - **[Error]** Unable to load file &#39;5.1/Microsoft.PowerShell.Utility/Export-Csv.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :226:(2398) &#39;```powershell
Get-Date | Format-Table -Property D...&#39;
 Expect Heading

<a name="reference%2F6%2FMicrosoft.PowerShell.Utility%2FExport-Csv.md"></a>
### [reference/6/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/6/Microsoft.PowerShell.Utility/Export-Csv.md)
 - **[Error]** Unable to load file &#39;6/Microsoft.PowerShell.Utility/Export-Csv.md&#39; via processor &#39;AzureCliDocumentProcessor&#39;: :227:(2447) &#39;```powershell
Get-Date | Format-Table -Property D...&#39;
 Expect Heading

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C7%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901072257248892-3515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=23StBzRLmzqzE0BW8eEZM%2BiWKsEaQ2bQod8kdadlEwE%3D&st=2019-01-07T23%3A06%3A17Z&se=2019-02-07T23%3A11%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3c28a67](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/3c28a670a2d3cbfe6a6df15c29d6f9ad53c0f1f9)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3c28a67](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/3c28a670a2d3cbfe6a6df15c29d6f9ad53c0f1f9)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 21 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[3c28a67](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/3c28a670a2d3cbfe6a6df15c29d6f9ad53c0f1f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-3.0&branch=pr-en-us-3515) (powershell-3.0) |
[reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-3.0&branch=pr-en-us-3515) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-4.0&branch=pr-en-us-3515) (powershell-4.0) |
[reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-4.0&branch=pr-en-us-3515) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-5.0&branch=pr-en-us-3515) (powershell-5.0) |
[reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-5.0&branch=pr-en-us-3515) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-5.1&branch=pr-en-us-3515) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-5.1&branch=pr-en-us-3515) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-6&branch=pr-en-us-3515) (powershell-6) |
[reference/6/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/6/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-6&branch=pr-en-us-3515) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901080418258069-3515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Itzxm%2B1FXEZjLcIJavy9Gy70uCk%2FAwSly3yCjDHweFE%3D&st=2019-01-08T04%3A27%3A08Z&se=2019-02-08T04%3A32%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c1cd770](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/c1cd770872267176b5f5d0c9feccacc1176b7b48)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c1cd770](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/c1cd770872267176b5f5d0c9feccacc1176b7b48)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 20 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[c1cd770](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/c1cd770872267176b5f5d0c9feccacc1176b7b48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/3.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-3.0&branch=pr-en-us-3515) (powershell-3.0) |
[reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/3.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-3.0&branch=pr-en-us-3515) (powershell-3.0) |
[reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/4.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-4.0&branch=pr-en-us-3515) (powershell-4.0) |
[reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/4.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-4.0&branch=pr-en-us-3515) (powershell-4.0) |
[reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.0/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-5.0&branch=pr-en-us-3515) (powershell-5.0) |
[reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.0/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-5.0&branch=pr-en-us-3515) (powershell-5.0) |
[reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.1/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-5.1&branch=pr-en-us-3515) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/5.1/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-5.1&branch=pr-en-us-3515) (powershell-5.1) |
[reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/6/Microsoft.PowerShell.Utility/ConvertTo-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/convertto-csv?view=powershell-6&branch=pr-en-us-3515) (powershell-6) |
[reference/6/Microsoft.PowerShell.Utility/Export-Csv.md](https://github.com/davidsmatlak/PowerShell-Docs/blob/ds-copyeditCSV/reference/6/Microsoft.PowerShell.Utility/Export-Csv.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.utility/export-csv?view=powershell-6&branch=pr-en-us-3515) (powershell-6) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201901081558287894-3515%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mlc2H1nNo1mB%2FdQ%2FdeOUAZIhhpx07vZHdJhuMg3oqtQ%3D&st=2019-01-08T16%3A06%3A58Z&se=2019-02-08T16%3A11%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[28de644](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/28de644c8fc9674bee8ef9aa6844a28c6d5546de)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[28de644](https://github.com/davidsmatlak/PowerShell-Docs/pull/3515/commits/28de644c8fc9674bee8ef9aa6844a28c6d5546de)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 19 sec(s)_

**Comment by davidsmatlak** [comment]
PR #3515 updated the Export-Csv Encoding parameter section for Issue #2000

**Pull request merged**
