### PR TITLE
Fix Enable-PsRemoting

### LINKED ISSUE #1026: Enable-PSRemoting.md is not properly formatted
Issue Details
-----------------
The Enable-PSRemoting cmdlet performs the following operations list is broken.

v3/v4 - the example headers are broken too

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document - just The Enable-PSRemoting cmdlet performs the following operations list
- [x] Impacts 5.0 document - just The Enable-PSRemoting cmdlet performs the following operations list
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### PR DESCRIPTION
**Pull request by zjalexander**
Fix #1026 for 3.0

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702220005355354-1060%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702220009275179-1060%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C2%5C22%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201702220010371763-1060%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@zjalexander Thanks for the detailed fix across all versions.

**Pull request merged**
