### PR TITLE
Update Learning-PowerShell-Names.md

### PR DESCRIPTION
**Pull request by doctordns**
Title changed to: Learning PowerShell command names. 
The title was originally Learning PowerShell names - but did not make it clear what kind of names.

### CODE REVIEW

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ca2ee3a](https://github.com/doctordns/PowerShell-Docs/pull/3485/commits/ca2ee3a73d96186b2b9a89888c6a798c6d04222e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 10 sec(s)_

**Comment by zjalexander** [comment]
OPS Build status updates of commit _[ca2ee3a](https://github.com/doctordns/PowerShell-Docs/pull/3485/commits/ca2ee3a73d96186b2b9a89888c6a798c6d04222e)_: 

:clock10: **Incremental building**: average incremental building time is _13 min(s) 22 sec(s)_

**Comment by doctordns** [comment]
@sdwheeler thanks for taking the PR. In general, how long does it take to get this updated content onto the docs.microsoft.com site?

**Comment by sdwheeler** [comment]
@doctordns I have been on vacation for the holiday season so PRs have been stalled. The push to the live site is a manual process. I try to do it at least once per week.

**Pull request merged**
