### PR TITLE
Remove digression on how to disable comment-based help

### PR DESCRIPTION
**Pull request by fsackur**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by sdwheeler** [comment]
@zjalexander @joeyaiello @SteveL-MSFT What are your thoughts on this change. I don't have a problem with it. But addition of this info predates me.

**Comment by SteveL-MSFT** [comment]
@HemantMahawar what are your thoughts on this?  This predates me, but the text seems out of place and (personally) not that useful

**Comment by zjalexander** [comment]
Hi @fsackur, I'm interested in hearing about your rationale for this change! I think the change is for the best, but your perspective is definitely welcomed. Do you think it's a bad practice we shouldn't endorse? Did you view it as just noise that prevented you from getting through the rest of the text? 

This information will help frame the conversation with a bit more clarity and help balance your perspective against the team's perspective. 

(For the record, I think it's not a useful scenario to cover in this topic, but I could see it being useful in another context)

**Comment by zjalexander** [comment]
I approve of these changes

**Pull request merged**
