### PR TITLE
Update Get-Date.md

### PR DESCRIPTION
**Pull request by jboeshart**
Minor fix to line layout in Example 9.

Version(s) of document impacted
------------------------------
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/jboeshart/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C3%5C24%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201703242130391315-1111%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@jboeshart,

would you be willing to update the other versions too?

Thanks in advance!!

**Comment by jboeshart** [comment]
Can do @juanpablojofre. Will update and add to this PR.

**Comment by jboeshart** [comment]
@juanpablojofre it looks like it was only an issue with the 5.1 & 5.0 versions of the document. I've corrected both versions and they are part of this PR. Let me know if you need anything else. Thanks!

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.0/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/jboeshart/PowerShell-Docs/blob/patch-1/reference/5.0/Microsoft.PowerShell.Utility/Get-Date.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md](https://github.com/jboeshart/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Utility/Get-Date.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C3%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704031302036451-1111%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
Thank you!

**Comment by jvierrajrv** [comment]
It might be useful to add the following:
```

$b = Get-WmiObject Win32_Bios
[System.Management.ManagementDateTimeConverter]::ToDateTime($b.ReleaseDate)

```
And this although not as current
```

# sortable date string useful for pre WMF 5
Get-Date -Format s

```

**Pull request merged**
