### PR TITLE
Update Get-EventLog.md

### PR DESCRIPTION
**Pull request by ygbae**
"Accept wildcard characters" properties of -Message, -Source, & -UserName parameters should be "True".

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [x] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Management/Get-EventLog.md](https://github.com/ygbae/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Management/Get-EventLog.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C11%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201704111322174539-1148%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@ygbae ,
If your update applies to other versions of PS, would you mind updating all other versions; if it doesn't would you please specify why it doesn't apply to other versions.
Remember to include PS6 in your analysis.
Best regards,
-- JP

**Comment by ygbae** [comment]
@juanpablojofre I am sorry my respond is late. I was on a business trip and wasn't able to check this in time. I am quite new to Github, so I am learning it day by day by the way. :-) 

As for PS6, this file doesn't exist for some reasons.

Best regards,
Y.G.

**Comment by zjalexander** [comment]
dupe of #1235

**Pull request closed without merging**
