### PR TITLE
reformatting and integrating changes from PR#1831

### PR DESCRIPTION
**Pull request by sdwheeler**
Integrated updates to Alias-Provider.md from PR #1831 and also reformatted with semantic linebreaks.

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

### CODE REVIEW

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/PowerShell/PowerShell-Docs, working directory: W:\zjju-s, target branch: staging, target branch commit: 518fde2ad8e8e11fa6ba5b8008692833e47a3018, source branch: 6809f03c7826ebcfb443fe6e60fe46e6/sdw-PR1831, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201711151901080492-1860%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=lPBdu6ETaKI%2BPbDpvsj3pGDJtkHpc3nvRZLE10O2%2FaA%3D&st=2017-11-15T19%3A02%3A42Z&se=2017-12-16T19%3A07%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit b20c2c1ced9338cdeb6c6a1d56dbf708ab3ff3e5 in branch sdw-PR1831 of repository https://github.com/sdwheeler/PowerShell-Docs into branch staging (commit 518fde2ad8e8e11fa6ba5b8008692833e47a3018)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201711151914173500-1860%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wISYTMQ6ToLP5%2FuncIt3XxcVLdNu8osndWWR0mGJliw%3D&st=2017-11-15T19%3A09%3A39Z&se=2017-12-16T19%3A14%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/3.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/3.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md) | :warning:Warning | | [Details](#user-content-reference%2F3.0%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md)
[reference/4.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/4.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md) | :warning:Warning | | [Details](#user-content-reference%2F4.0%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md)
[reference/5.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/5.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md) | :warning:Warning | | [Details](#user-content-reference%2F5.0%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md)
[reference/5.1/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/5.1/Microsoft.PowerShell.Core/Providers/Alias-Provider.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md)
[reference/6/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/6/Microsoft.PowerShell.Core/Providers/Alias-Provider.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md)

<a name="reference%2F3.0%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md"></a>
### [reference/3.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/3.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F4.0%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md"></a>
### [reference/4.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/4.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.0%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md"></a>
### [reference/5.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/5.0/Microsoft.PowerShell.Core/Providers/Alias-Provider.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/5.1/Microsoft.PowerShell.Core/Providers/Alias-Provider.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FProviders%2FAlias-Provider.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Providers/Alias-Provider.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-PR1831/reference/6/Microsoft.PowerShell.Core/Providers/Alias-Provider.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201711151916191596-1860%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=sfW9uiizz7%2BIitiJaERzqeRnUzaPKrz%2FL0rJVX3iKyk%3D&st=2017-11-15T19%3A39%3A12Z&se=2017-12-16T19%3A44%3A12Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by sdwheeler** [comment]
@zjalexander - Please review and merge.

**Pull request merged**
