### PR TITLE
Make AppVeyor build fail on platyPS errors

### PR DESCRIPTION
**Pull request by vors**
This is a part of #798
We want to fail the build, if there are platyPS errors.
Example: #820

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[appveyor.ps1](https://github.com/vors/PowerShell-Docs/blob/appveyor/appveyor.ps1) | :white_check_mark:Succeeded | | [Details](#user-content-appveyor.ps1)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611180144422432-822%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by vors** [comment]
Looks like I would need to re-do this with `try-catch`.
ErrorVarable contains too much noise.
Hold on a little bit.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[appveyor.ps1](https://github.com/vors/PowerShell-Docs/blob/appveyor/appveyor.ps1) | :white_check_mark:Succeeded | | [Details](#user-content-appveyor.ps1)


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C18%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201611180210193259-822%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by vors** [comment]
Cool, so looks like after merging #821, everything should work.
In the [latest build](https://ci.appveyor.com/project/PowerShell/powershell-docs/build/1.0.120) there are only two failures and they are fixed in #821 

🙏

**Pull request merged**
