### PR TITLE
Update about_History.md

### PR DESCRIPTION
**Pull request by doctordns**
Small change to a table to keep items in the same cell under the "to perform this action" column.

Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_History.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-18/reference/5.1/Microsoft.PowerShell.Core/About/about_History.md) | :warning:Warning | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_History.md)

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Core%2FAbout%2Fabout_History.md"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_History.md](https://github.com/doctordns/PowerShell-Docs/blob/patch-18/reference/5.1/Microsoft.PowerShell.Core/About/about_History.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C20%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201710200859263068-1792%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aPWXFyb3SNthp2DvG%2BPRJZuQ5%2F%2FOIIp2OolwLjLERbo%3D&st=2017-10-20T09%3A21%3A44Z&se=2017-11-20T09%3A26%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by matt9ucci** [comment]
@juanpablojofre This table was broken by #1782 😔 There are many other problems in the PR. Please consider to roll back or review it.

**Comment by juanpablojofre** [comment]
Thomas, @doctordns,
Thanks for your contributions, I find them invaluable.
But, this one I cannot accept it because it breaks the build for the updatable help on About_* topics.
I know it differs with the styling guide!
We'll fix the style guide to describe how to write for About topics.
Thanks!!

**Comment by juanpablojofre** [comment]
Matt, @matt9ucci ,
We are working on completing the build process; so, it includes About_* topics in the cab files, in an automated way. In the past, each About_* topic was manually generated as text file and included in the build process.
I understand your frustration, but bear with us this rough moment. We'll have a better and cleaner build system that in the near future will create the cabs for updatable help every time we build for Live.

**Comment by doctordns** [comment]
I am not sure what I broke. I just (tried to) change two lines in a table?
So far as I know I am not responsible for 'many other problems' :-)

**Comment by juanpablojofre** [comment]
Thomas!!!
You didn't break anything. On the contrary, you have helped us build a better documentation for PowerShell.

What I meant was that I couldn't merge your PR because it would break, in the near future, the About_* topics build.

Please, keep your contributions coming.

**Comment by matt9ucci** [comment]
@doctordns I also think you didn't break anything. In fact, I had submitted #1789 that was similar to your PR.

**Pull request closed without merging**
