### PR TITLE
a few typos and formatting changes

### PR DESCRIPTION
**Pull request by lazywinadmin**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [ ] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/lazywinadmin/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C20%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706200054197363-1349%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@lazywinadmin, Thanks so much for your contribution; it's greatly appreciated.

Could you please change those triple backticks in line 50+ to single backtick.

Inline fenced code uses single backtick; triple backticks are used to do code blocks.

Thanks again.
juanpablo.jofre

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/lazywinadmin/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C21%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706210455183727-1349%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[gallery/psgallery/psgallery-PublishingGuidelines.md](https://github.com/lazywinadmin/PowerShell-Docs/blob/staging/gallery/psgallery/psgallery-PublishingGuidelines.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C6%5C21%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201706210457146301-1349%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
Thanks @lazywinadmin !!

**Pull request merged**
