### PR TITLE
Adding PR and ISSUE templates

### PR DESCRIPTION
**Pull request by HemantMahawar**
@eslesar @juanpablojofre @zjalexander can you take a look at it. /cc @joeyaiello 
Will add an issue template as well.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C24%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701241943205528-987%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701252129028364-987%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701252133143300-987%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C25%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701252135118531-987%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
👍

**Pull request merged**
