### PR TITLE
Clarify the use of PasswordPass option

### PR DESCRIPTION
**Pull request by ebekker**
Version(s) of document impacted
------------------------------
- [ ] Impacts 6.1 document
- [ ] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

Reason(s) for not updating all version of documents
--------------------------------------------------
- [ ] The documented feature was introduced in version (list version here) of PowerShell
- [x] This issue only shows up in version (list version(s) here) of the document
- [ ] This PR partially fixes the issue, and issue #<insert here> tracks the remaining work

### CODE REVIEW

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md](https://github.com/ebekker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C20%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805201504024131-2447%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fm3Oc7GPFFYwp%2B6tAr27eS1JlxdGLYTrsTtmD5eSGVQ%3D&st=2018-05-20T15%3A09%3A58Z&se=2018-06-20T15%3A14%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md](https://github.com/ebekker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md) | :x:Error | | [Details](#user-content-reference%2F5.1%2FMicrosoft.PowerShell.Management%2FAdd-Computer.md)
[]() | :x:Error | | [Details](#user-content-)

<a name="reference%2F5.1%2FMicrosoft.PowerShell.Management%2FAdd-Computer.md"></a>
### [reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md](https://github.com/ebekker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md)
 - **[Error]** Unable to load file: 5.1/Microsoft.PowerShell.Management/Add-Computer.md via processor: AzureCliDocumentProcessor: :109:(1315) &#39;```
PS C:\&gt; $joinCred = New-Object pscredential -...&#39;
 Expect Heading

<a name=""></a>
### []()
 - **[Error]** Markdown.MAML.Transformer.HelpSchemaException: :109:(1315) &#39;```
PS C:\&gt; $joinCred = New-Object pscredential -...&#39;
 Expect Heading
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.GetInnerContexts(DocumentBuildParameters parameters, IEnumerable`1 processors, TemplateProcessor templateProcessor, IHostServiceCreator creator)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
 - **[Warning]** No file found, nothing will be generated. Please make sure docfx.json is correctly configured.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C20%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805202044467168-2447%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tlHIiZZ7FuYbVnY4UPQoHUr7%2BsGoAuZMGyEXUAlwDmk%3D&st=2018-05-20T20%3A46%3A39Z&se=2018-06-20T20%3A51%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ebekker** [comment]
Is this validation error just some bug in the build process or did I genuinely screw something up?  I tried to make my example addition follow the same pattern and structure as the existing ones.

**Comment by sdwheeler** [comment]
close and reopen to retrigger the build

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md](https://github.com/ebekker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C21%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805210231267878-2447%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5%2F9hyJJHnrmrZcNZZTl0szvnER%2Fijug1lG9RKwNaI9Y%3D&st=2018-05-21T02%3A36%3A39Z&se=2018-06-21T02%3A41%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by zjalexander** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md](https://github.com/ebekker/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Management/Add-Computer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C21%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201805210232236386-2447%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2Bk4F42F%2BQerwGtBahXCD%2B6yF1ZzZaeSKLBWXXtTIJUc%3D&st=2018-05-21T02%3A47%3A42Z&se=2018-06-21T02%3A52%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ebekker** [comment]
Ah, I was wondering if it was talking about the language indicator of the code block, but assumed not since the existing ones didn't have it.  Thank you!

**Comment by sdwheeler** [comment]
@ebekker It was not the language indicator on the code block. The issue with the schema is that, in an example, you cannot have text between code blocks. I have filed a bug for PlatyPS to fix that.

**Comment by ebekker** [comment]
Ah, I see -- I just saw your addition to add the `powershell` language tag and assumed that was the fix.

Good to know, thanks!

**Pull request merged**
