### PR TITLE
Updating Live with recent changes.

### PR DESCRIPTION
**Pull request by juanpablojofre**
@eslesar, @HemantMahawar 
Please take a look at this request.

### CODE REVIEW

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C11%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701111837294434-948%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C11%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701112301288963-948%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C11%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701112302468839-948%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by HemantMahawar** [comment]
@juanpablojofre  Looks like Push-Location.md (in 5.1 folder) is missing 'external help file' metadata.
Could have been introduced by #898.
Please fix the issue so CI builds can succeed \cc @eslesar

**Comment by juanpablojofre** [comment]
@HemantMahawar, CI builds completed successfully!!
See: 

- [continuous-integration/appveyor/branch](https://ci.appveyor.com/project/PowerShell/powershell-docs/build/1.0.301)
- [continuous-integration/appveyor/pr](https://ci.appveyor.com/project/PowerShell/powershell-docs/build/1.0.302)

Could you, please, merge this PR?
\cc @eslesar

**Comment by saldana** [comment]
### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C1%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201701121859581517-948%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
