### PR TITLE
Added new SSH parameter set info to Enter-PSSession cmdlet

### PR DESCRIPTION
**Pull request by PaulHigin**
Added documentation for new SSHHost parameter set in Enter-PSSession.
There are three cmdlets that have been updated for SSH base remoting:
Enter-PSSession
New-PSSession
Invoke-Command

### CODE REVIEW

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C12%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707122309450199-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by PaulHigin** [comment]
@juanpablojofre  I already see some errors I want need to fix for the Enter-PSSession cmdlet.  I also want to add similar information for New-PSSession and Invoke-Command cmdlets in this PR, so please be aware that I will be adding more commits in the next couple of days.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707131707596261-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707132136323881-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707132200189341-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)
[reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md)
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C13%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707132319364690-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by juanpablojofre** [comment]
@PaulHigin,
Can you fix some of the headings in the documents?
PlatyPS is complaining that some headings are level 4 (####) when they should be level 3 (###).

Please review the details in the failing Appveyor CI.

Thanks again for your contribution.
-- JP

**Comment by PaulHigin** [comment]
@juanpablojofre 
I was using level 4 headings (####) to split up the -Port parameter discussion.  It is now used both for WinRM and SSH remoting so I made two sub sections to discuss -Port for each case.  Please let me know if there is a better way to do this.

I don't understand these warnings.  It seems that all md files have them.  Can you tell me how to fix it for these three files?

**Comment by juanpablojofre** [comment]
The warnings are generated by the Locale metadata tag. 
Which is used by PlatyPS but 'rejected' by the build system that ports these documents to MSDN.
You can ignore them.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)
[reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md)
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C27%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707270039396934-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)
[reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md)
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C27%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707270111342880-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by saldana** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md)
[reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md)
[reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md) | :warning:Warning | | [Details](#user-content-reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md)

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FEnter-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Enter-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FInvoke-Command.md"></a>
### [reference/6/Microsoft.PowerShell.Core/Invoke-Command.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/Invoke-Command.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

<a name="reference%2F6%2FMicrosoft.PowerShell.Core%2FNew-PSSession.md"></a>
### [reference/6/Microsoft.PowerShell.Core/New-PSSession.md](https://github.com/PaulHigin/PowerShell-Docs/blob/SSHCmdletUpdate/reference/6/Microsoft.PowerShell.Core/New-PSSession.md)
 - **[Warning]** Ignore metadata: locale. They are generated by open publish.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C7%5C27%5Cbab27324-4c59-a348-1473-9c6d587e4020%5CPullRequest%5C201707271604342178-1439%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
